### ISSUE TITLE
Event emmitter

### ISSUE THREAD

**Issue by hishamibrah** [veliovgroup/Meteor-Files#837] opened 2022-05-26 13:33 UTC
I'm having an issue: 
returnMeta returning a event emmiter  on file server.js line 788 because of which the check is being failed.

**Comment by dr-dimitru** [comment] 2022-06-08 21:42
@hishamibrah can you post an error or exception you experiencing ?

**Comment by dr-dimitru** [comment] 2022-06-29 08:19
@hishamibrah 
Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment] 2022-09-16 08:56
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Closed by dr-dimitru** 2022-09-16 08:56 UTC
Labels: Need More Info
