### ISSUE TITLE
Error during upload: TypeError: Images.write is not a function

### ISSUE THREAD

**Issue by badis** [VeliovGroup/Meteor-Files#520] opened 2017-11-19 22:38 UTC
I am getting error: `Error during upload: TypeError: Images.write is not a function` when trying to upload an image on server.
I am using:
ostrio:files
meteor-base@1.0.4   

Server code:

```
export const insertImage = new ValidatedMethod({
  name: 'images.insert',
  validate: new SimpleSchema({
    file: { type: String },
  }).validator(),
  run({ file }) {
    console.log(file);
    Images.write(file, {
      fileName: 'sample.png',
      fielId: 'abc123myId', // optional
      type: 'image/png',
    }, function (error, fileRef) {
      if (error) {
        throw error;
      } else {
        console.log(`${fileRef.name} is successfully saved to FS. _id: ${fileRef._id}`);
      }
    });
  },
});

```

Client code: 
```
  const images = document.querySelector('[name="images"]').files;

  if (images && images.length > 0) {
    const { doc } = component.props;
    const confirmation = doc && doc._id ? 'Document updated!' : 'Document added!';
    const upsert = {
      title: document.querySelector('[name="title"]').value.trim(),
      body: document.querySelector('[name="body"]').value.trim(),
      images: [],
    };

    if (doc && doc._id) upsert._id = doc._id;
    const imagesId = [];
    const reader = new FileReader();
    Array.from(images).map((image) => {
      reader.addEventListener('load', () => {
        insertImage.call({ file: reader.result }, (err, res) => {
          if (err) {
            console.log(`Error during upload: ${err}`);
          } else {
            imagesId.push(res.insertedId);
            if (imagesId.length === images.length) {
              upsertDocument.call(upsert, (error, response) => {
                if (error) {
                  Bert.alert(error.reason, 'danger');
                } else {
                  component.documentEditorForm.reset();
                  Bert.alert(confirmation, 'success');
                  if (upsert._id) browserHistory.push(`/documents/${response.insertedId}`);
                }
              });
            }
          }
        });
      }, false);
      reader.readAsDataURL(image);
    });

  } 

```

https://imgur.com/a/bFf77

Thank you !

**Comment by stefanve** [comment] 2017-11-20 05:39
How did you define the Images collection?

**Comment by badis** [comment] 2017-11-20 10:05
Like this: 

```
import { Meteor } from 'meteor/meteor';
import { FilesCollection } from 'meteor/ostrio:files';
import { BrowserPolicy } from 'meteor/browser-policy';

if (Meteor.isServer) {
  Meteor.startup(() => {
    BrowserPolicy.content.allowOriginForAll('blob:');
  });
}

const Images = new FilesCollection({ debug: true, collectionName: 'images',
  storagePath: () => {
    if (Meteor.isServer) {
      return process.env.PWD + '/uploads';
    }
    return '';
  },
});

export default Images;
```

**Comment by dr-dimitru** [comment] 2017-11-20 13:29
Hello @badis 

 1. [`.write`](https://github.com/VeliovGroup/Meteor-Files/wiki/Write) is *Server* only method, in your screenshot I see you're getting this error in a browser.
 2. For file upload from *Client* (browser) you should use [`.insert()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload))
 3. No need to protect `storagePath` with `if isServer` block as `storagePath` is not available on the *Client*

**Comment by badis** [comment] 2017-11-20 13:53
Hi @dr-dimitru . Thank you for your reply !

1. Yes, I am using `.write` in a Method definition only server (server code above). The error happened in server and returned to client in `err` argument. I displayed it in this line : `console.log(`Error during upload: ${err}`);`
2. I am using react native and react-native-meteor package to communication with server. but for some reason I can't import and use a collection on mobile (client). so that's why I have used a method call on client to send base64 encoded file to server.
3. Because sometimes I use Images collection (in images.js) on web client. that's why I have add `isServer` to avoid issues.

So to resume, I am using : method.js (only server) . upsertDocument.js (only client) . images.js (Shared)

**Comment by dr-dimitru** [comment] 2017-11-20 13:58
I need more info, please update with info from our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):
  - Version of `Meteor-Files` you're experiencing this issue
  - Version of `Meteor` you're experiencing this issue
  - Is it *Client* or *Server* issue (`meteor --version`)?
  - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

**Comment by badis** [comment] 2017-11-20 14:45
@dr-dimitru  . I think I have made a mistake in Method calls. I will try again and let you know. Thank you !

**Comment by badis** [comment] 2017-11-21 16:38
@dr-dimitru . It is my mistake because i was importing method code in client side which is not good for my use case. So instead of doing this: 
```
import { insertImage } from '../api/files/images/methods';
insertImage.call( { file: reader.result }, (err, res) => { ....
```

I should do this :

` Meteor.call('images.insert', { file: reader.result }, (err, res) => { ... `

So this answered my questions and I am able to send a base64 encoded file to server without errors.
But I am encountering 3 other issues.

I will try to describe them in new issue.

**Comment by dr-dimitru** [comment] 2017-11-21 16:47
Feel free to close it in case if the issue is solved. ty.

**Closed** 2017-11-21 16:51 UTC
Labels: .insert() (upload), .write(), question
