### ISSUE TITLE
Error calling findOne function

### ISSUE THREAD

**Issue by minhna** [VeliovGroup/Meteor-Files#756] opened 2020-08-24 10:33 UTC
I'm having a weird issue. The code is very simple, I just call the findOne function on the server
```
const theFile = FilesServer.findOne({ _id: someIdHere });
```
But I've got this error:
```
20200824-17:09:45.645(7)? (STDERR) (node:37318) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
W20200824-17:09:45.647(7)? (STDERR)     at isObject (packages/ejson/utils.js:3:26)
W20200824-17:09:45.647(7)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:553:8)
W20200824-17:09:45.648(7)? (STDERR)     at packages/ejson/ejson.js:600:22
W20200824-17:09:45.648(7)? (STDERR)     at Array.forEach (<anonymous>)
W20200824-17:09:45.648(7)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
W20200824-17:09:45.649(7)? (STDERR)     at packages/ejson/ejson.js:600:22
W20200824-17:09:45.649(7)? (STDERR)     at Array.forEach (<anonymous>)
W20200824-17:09:45.650(7)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
W20200824-17:09:45.650(7)? (STDERR)     at packages/ejson/ejson.js:600:22
W20200824-17:09:45.651(7)? (STDERR)     at Array.forEach (<anonymous>)
W20200824-17:09:45.651(7)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
W20200824-17:09:45.652(7)? (STDERR)     at packages/ejson/ejson.js:600:22
W20200824-17:09:45.652(7)? (STDERR)     at Array.forEach (<anonymous>)
W20200824-17:09:45.653(7)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
W20200824-17:09:45.653(7)? (STDERR)     at packages/ejson/ejson.js:600:22
W20200824-17:09:45.654(7)? (STDERR)     at Array.forEach (<anonymous>)
W20200824-17:09:45.654(7)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
W20200824-17:09:45.667(7)? (STDERR)     at packages/ejson/ejson.js:600:22
W20200824-17:09:45.668(7)? (STDERR)     at Array.forEach (<anonymous>)
W20200824-17:09:45.668(7)? (STDERR)     at Object.EJSON.clone (packages/ejson/ejson.js:599:13)
W20200824-17:09:45.668(7)? (STDERR)     at packages/ejson/ejson.js:600:22
W20200824-17:09:45.669(7)? (STDERR)     at Array.forEach (<anonymous>)
W20200824-17:09:45.675(7)? (STDERR) (node:37318) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
W20200824-17:09:45.686(7)? (STDERR) (node:37318) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

In order to fix it, I had to change it to `.find` function. then it works.
```
const theFile = FilesServer.find({ _id: someIdHere }).fetch();
```

ostrio:files@1.14.2
meteor 1.11
ejson@1.1.1
os: ubuntu 20.04

**Comment by kakadais** [comment] 2020-09-04 21:23
I believe that you should upload or capture here, actual saved file collection data to be analyzed.

**Comment by dr-dimitru** [comment] 2020-09-16 11:32
@minhna can you post logs with `debug` being enabled?
The quick guess — you're sending `File` cursor from server to client

**Comment by minhna** [comment] 2020-09-16 12:15
> @minhna can you post logs with `debug` being enabled?
> The quick guess — you're sending `File` cursor from server to client

You're right. That's my fault.

**Comment by dr-dimitru** [comment] 2020-09-16 12:19
Feel free to close it in case if the issue is solved on your end. @minhna

**Closed** 2020-09-16 13:14 UTC
Labels: question
