### ISSUE TITLE
Upload is very slow and pauses on files of atleast 600Mb

### ISSUE THREAD

**Issue by PhilMataz** [VeliovGroup/Meteor-Files#733] opened 2020-03-23 11:20 UTC
### I'm having an issue:

Description: 

Firstly, uploads are at 0.4Mbps even thought it should be 5Mbps.
Secondly, when I upload a file of 600Mb, the upload pauses. This randomly happens with smaller file sizes as well. 
I have also experienced the internet going off (only on that particular machine), once I start an upload. This does not affect other devices in the network. Upload on my desktop, internet goes off on that machine, everything else is fine. I upload on my laptop, internet goes off on that machine, all other machines are fine. This happens irregularly. 

Meteor-Files version:  1.11.1*

Meteor version: 1.8.1

Windows version: 10.0.18362

Chrome version: 80.0.3987.149

It seems to be a client issue.

Client Logs: 

![image](https://user-images.githubusercontent.com/11684246/77311019-9d50cd00-6cff-11ea-925c-fee60df5a288.png)

Server Logs: 

![image](https://user-images.githubusercontent.com/11684246/77311296-18b27e80-6d00-11ea-9275-1b6e48e23b98.png)

I'm using nginx as a reverse proxy, this is the nginx config:

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        client_max_body_size 1024M;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}


#mail {
#       # See sample authentication script at:
#       # http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#       # auth_http localhost/auth.php;
#       # pop3_capabilities "TOP" "USER";
#       # imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#       server {
#               listen     localhost:110;
#               protocol   pop3;
#               proxy      on;
#       }
#
#       server {
#               listen     localhost:143;
#               protocol   imap;
#               proxy      on;
#       }
#}

```

Best regards

**Comment by kakadais** [comment] 2020-03-25 19:59
If it is true, that would be critical,
but in my case, I used to use this package on a lot of environment include linux/windows/mac with various networks, but I couldn't see it before.

I'm not specialist on this project but if the whole internet connection was closed by some action, I think we could assume it that the operation system and network driver or router itself could have some problem than the software it has. Cause that's OS/network driver's job we expected.

So could you please clearly test the same one on the other OS(linux or mac) and on the other network(cloud. whatever.)?

Thanks a lot-

**Comment by dr-dimitru** [comment] 2020-03-26 22:38
Hello @PhilMataz ,

Thank you for reporting this.
I'm agree with @kakadais as this package is out for a while and through all years it's the first time we got this kind of report.

While we're investigating this issue (hope there will be someone else with similar report) here's quick list of what can solve the issue:

1. Change `transport` to `http`, I believe issue in DDP/WebSockets overhead;
2. Change `dynamic` `chunkSize` to something small like `64`, `128`, `256` try few options to match your needs;
3. Change `dynamic` `streams` to `1`;
4. Prepare minimal reproduction test-repo, so other can test it on their environment.

Thank you. Please, keep us updated.

//cc @jankapunkt have you seen anything like this before?

**Comment by jankapunkt** [comment] 2020-03-26 22:44
I for myself can only add that I observed `websocket frame length too large` when I tried to moved many documents that sum up to about this size. Not 100% related to this package, since I moved them over standard DDP method.

**Comment by dr-dimitru** [comment] 2020-05-02 16:49
Hello @PhilMataz ,

Have you tried suggested options?

**Comment by dr-dimitru** [comment] 2020-06-17 19:02
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Closed by dr-dimitru** 2020-06-17 19:02 UTC
Labels: .insert() (upload), Need More Info, question
