### ISSUE TITLE
Empty File Data On 1.7.1

### ISSUE THREAD

**Issue by livimonte** [VeliovGroup/Meteor-Files#203] opened 2016-08-26 11:48 UTC
Hi, 

After update for Meteor: 1.4.1.1 and 1.7.1 some data of files (like extension) is now empty.

1.7.0 (1.4.1.1) - OK
![screen shot 2016-08-26 at 08 31 07](https://cloud.githubusercontent.com/assets/1934765/18004218/d2660844-6b68-11e6-9de2-e685396855bd.png)

1.7.1 (1.4.1.1) - ERROR
![screen shot 2016-08-26 at 08 34 00](https://cloud.githubusercontent.com/assets/1934765/18004219/d2669336-6b68-11e6-9529-38ed39317d93.png)

Tested: OSX 10.9.5 And Ubuntu 14 (64x).

**Comment by dr-dimitru** [comment] 2016-08-26 12:30
Hi @livimonte ,

Thank you for report, investigating....

**Comment by dr-dimitru** [comment] 2016-08-27 09:17
Hey @livimonte ,
Started working on this one. No issues persists on my end. Then red your question again.
Turns out on the second screenshot you're uploading file without extension, see `file` prop

**Comment by dr-dimitru** [comment] 2016-08-28 06:48
@livimonte could you please respond to previous message?

**Comment by livimonte** [comment] 2016-08-28 14:56
Hi @dr-dimitru ,

The second file has no extension because the property came empty in the naming function. For the lack of extension it was renamed wrong.

**Comment by dr-dimitru** [comment] 2016-08-28 14:58
Post collection configuration

**Comment by livimonte** [comment] 2016-08-28 15:13
Of course:

```javascript
HistoriesFiles = new FilesCollection({
  debug: Meteor.settings.public.debug,
  collectionName: 'historiesFiles',
  storagePath: uploadRootPath + '/uploads/histories',
  downloadRoute: '/images/histories',
  allowClientCode: false, // Disallow remove files from Client
  public: true,
  namingFunction: function (file){
    const newName = Helpers.upload.rename(file.name);
    file.name = newName;
    return newName;
  },
  onBeforeUpload: function (file) {
    file.name = Helpers.slugFileName(file.name);
    return true;
  },
});

//Rename Helper
    rename(name){
      return Random.id() + '-' + Helpers.slugFileName(name, false);
    },

//slugFileName Helper
slugFileName(_name, withExt = true){
    let clearName;
    const name = _name.toLowerCase(),
      ext = name.split('.').pop(),
      extReplace= '-'+ext,
      extFile = '.'+ext,
      slugName = s.slugify(name),
      replace = withExt ? extFile : '';
    
    clearName = slugName.replace(new RegExp(extReplace + '$'), replace);
    return clearName.toLowerCase();
  },

```

**Comment by dr-dimitru** [comment] 2016-08-28 17:48
Can not reproduce, tested on:
```js
Collections.files = new FilesCollection({
  storagePath: 'assets/app/uploads/uploadedFiles',
  collectionName: 'uploadedFiles',
  allowClientCode: true,
  onBeforeUpload: function() {
    console.log(this, arguments);
    return true
  },
  namingFunction: function(file) {
    file.name = 'asdasd.png';
    return 'asdasd.png';
  }
});
```

![screen shot 2016-08-28 at 8 47 38 pm](https://cloud.githubusercontent.com/assets/1686778/18035558/b6b3bad4-6d60-11e6-8d36-49ab878b5bfe.png)


Please check what helpers `rename` and `slugFileName` actually returning

**Comment by livimonte** [comment] 2016-08-28 18:01
I'll check again when i back to this project, probably tuesday. Thanks.

**Comment by dr-dimitru** [comment] 2016-08-30 13:15
Hey @livimonte ,
Please update to v1.7.2, there was various fixes

**Comment by livimonte** [comment] 2016-08-30 16:30
Hi @dr-dimitru,

I tried for two hours but unfortunately I could not figure out why it works on 1.7.2/1.7.0 and not in 1.7.1. But it works.

Offtopic: The delay of the meteor's build is discouraging. Any trick to help it will be welcome.

Thank you very much.

**Comment by dr-dimitru** [comment] 2016-08-30 18:18
What do you mean?

> The delay of the meteor's build is discouraging

Dev or prod?

**Comment by livimonte** [comment] 2016-08-30 18:38
Dev, about 10-15 seconds for restart and that ended my time to finish most significant tests of this bug. But it is not a problem related to Meteor Files.

I think you can close this issue as it worked in this release.

Thanks again,
Best.

**Comment by dr-dimitru** [comment] 2016-08-30 18:48
>  about 10-15 seconds for restart and that ended my time 

Meteor not so reactive these days. But may be you have a lot TS, CS pt ES6 files?

> But it is not a problem related to Meteor Files

Oh, okay, I thought it is.

> I think you can close this issue as it worked in this release.

I prefer issue owner close it as confirmation

**Closed by dr-dimitru** 2016-08-30 18:48 UTC
Labels: bug, invalid

**Comment by livimonte** [comment] 2016-08-30 19:12
> Meteor not so reactive these days. But may be you have a lot TS, CS pt ES6 files?

Only ES6 files. I will look at Webpack, but I need to find something more stable with blaze. Thanks anyway.

> I prefer issue owner close it as confirmation

Roger That
