### ISSUE TITLE
How to get link file after upload in Meteor Files 

### ISSUE THREAD

**Issue by Saeeed-B** [veliovgroup/Meteor-Files#769] opened 2020-11-04 10:42 UTC
Hi, I am uploading my text editor (Quil Editor) files using React and Meteor-Files.
But I do not know exactly how to get the link after uploading and put it in the editor.
Do I have to subscribe to get the link to that file after upload?
And if so. Is there a way to subscribe to that file right away?
Note that I have to subscribe to this file in such a way that I can get the file link in the same method (UploadImage)

Because if I subscribe to it as a withTracker, this method will not be rendered again so that I can get the link to that file. 

I asked here too and sied more :
[https://forums.meteor.com/t/how-to-get-link-file-after-upload-in-meteor-files/54432](https://forums.meteor.com/t/how-to-get-link-file-after-upload-in-meteor-files/54432)

**Comment by dr-dimitru** [comment] 2020-11-04 16:30
Hello @Saeed-Bahrami ,

1. Subscribing is one of the options;
2. No, it's optional

I updated [`.link()` method documentation](https://github.com/veliovgroup/Meteor-Files/blob/master/docs/link.md), hope now this method usage will be more straightforward.

TL;TR; You have next options:

1. After upload on server and client hooks you can get `fileRef` the copy of the *file* object from MongoDB record; Using this record you can do [`FilesCollection#link(fileRef)`](https://github.com/veliovgroup/Meteor-Files/blob/master/docs/link.md)
2. __Not the best option__ other way is to subscribe and use `FilesCollection#find().link()`

Feel free to close it in case if the issue is solved on your end.

**Comment by Saeed-Bahrami** [comment] 2020-11-04 18:09
@dr-dimitru 
I'm sorry, but I still did not understand correctly.
As I realized, the following code should work, and without subscribing, I should get the link after uploading.
```
 const upload = ImgCollection.insert({
           file: Img,
           streams: 'dynamic',
           chunkSize: 'dynamic'
 }, false);

console.log(upload);
            
upload.start();

const file = ImgCollection.findOne({_id:`${upload.config.fileId}`});
console.log(file.link());
```

**Comment by Saeed-Bahrami** [comment] 2020-11-04 18:21
> @dr-dimitru
> I'm sorry, but I still did not understand correctly.
> As I realized, the following code should work, and without subscribing, I should get the link after uploading.
> 
> ```
>  const upload = ImgCollection.insert({
>            file: Img,
>            streams: 'dynamic',
>            chunkSize: 'dynamic'
>  }, false);
> 
> console.log(upload);
>             
> upload.start();
> 
> ...........

but i get **undefined**

**Comment by dr-dimitru** [comment] 2020-11-04 18:27
> As I realized, the following code should work, and without subscribing, I should get the link after uploading.

1. __Yes, on server__
2. __No, on client__

Listen for `end` event on the Client as in the example link from my message above. Something like that: 

```js
 const upload = ImgCollection.insert({
  file: img
}, false).on('end', function (error, fileObj) {
  // get link in here
  console.log(ImgCollection.link(fileObj))
}).start();
upload.start();
```

**Comment by Saeed-Bahrami** [comment] 2020-11-04 18:34
@dr-dimitru 
It was great, he answered.
Thank you for your prompt and accurate response

**Comment by kakadais** [comment] 2020-11-05 02:57
> It was great, he answered.
yeah, he answered kk

**Comment by dr-dimitru** [comment] 2020-11-05 15:19
@Saeed-Bahrami I'm glad this issue was quickly solved

Please support this project with:
 - [Become a sponsor on GitHub](https://github.com/sponsors/dr-dimitru) and GitHub __would double your every contribution__ in next 12 months!;
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Star this package on GitHub;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Check out our [other open source projects on GitHub](https://github.com/veliovgroup).

**Comment by Saeeed-B** [comment] 2021-01-22 13:48
@dr-dimitru Hello again.
I got the image link the same way, and save it in the database so I can display it later.
But after a while (I do not know exactly how many hours) the links expire and error 404 returns.
Do the links expire?
What method should we use to always display images?

**Comment by Saeeed-B** [comment] 2021-01-22 13:49
@dr-dimitru Hello again.
I got the image link the same way, and save it in the database so I can display it later.
But after a while (I do not know exactly how many hours) the links expire and error 404 returns.
Do the links expire?
What method should we use to always display images?

**Comment by dr-dimitru** [comment] 2021-01-22 15:15
@Saeeed-B it sounds to me that you ran into different issue described in our [FAQ](https://github.com/veliovgroup/Meteor-Files#faq):

- Note: __All files will be removed as soon as your application rebuilds or you run `meteor reset`.__ To keep your storage persistent during development use an absolute path outside of your project folder, e.g. `/data` directory.

If it's not the case, I'll request more details

**Comment by dr-dimitru** [comment] 2021-01-27 15:34
@Saeeed-B is this one solved o you end? You haven't replied since my comment

**Closed** 2021-01-27 15:33 UTC
Labels: question

**Comment by Saeeed-B** [comment] 2021-01-28 15:46
@dr-dimitru Hi, thank you for your help, I have to test Rahel.
I will definitely report if I see a problem
Thanks
