### ISSUE TITLE
file.link() gives  _id instead of filename

### ISSUE THREAD

**Issue by blockracers** [veliovgroup/Meteor-Files#761] opened 2020-10-12 07:49 UTC
I've tried interceptDownload and setting filename on insert, I use a custom naming function and I'm trying to figure out how to have that same name (as fs stores file as) on download? Any help appreciated/

**Comment by dr-dimitru** [comment] 2020-10-12 09:41
@blockracers speak code.

1. Share code you already have
2. What do you want as a result?

**Comment by blockracers** [comment] 2020-10-13 07:19
```
export const UploadedDocumentFiles = new FilesCollection({
  ...newCollectionOptions,
  namingFunction,
  collectionName: "uploadedDocumentFiles",
  storagePath: uploadedDocsFilePath,
  async onAfterUpload(file) {
    if (Meteor.isServer) {
      const { mime } = await FileType.fromFile(file.path);
      if (!docTypes.includes(mime)) {
        console.log("onAfterUpload, not an correct doc type: ", file.path);
        console.log("deleted", file.path);
        this.remove(file._id);
        // throw new Meteor.Error("File not a pdf or Word doc");
      }
    }
  },
  interceptDownload(http, fileRef, version) {
    console.log("Intercepting download");
    const downloadFileName = "what"; //version.substring("renamed-download".length + 1, version.length);
    const dispositionType = "attachment; ";
    const dispositionName = `filename=\"${encodeURI(downloadFileName).replace(
      /\,/g,
      "%2C"
    )}\"; filename*=UTF-8''${encodeURIComponent(downloadFileName)}; `;
    const dispositionEncoding = "charset=UTF-8";

    if (!http.response.headersSent) {
      console.log("Setting headers");
      http.response.setHeader(
        "Content-Disposition",
        dispositionType + dispositionName + dispositionEncoding
      );
    }

    console.log(fileRef, version);
    // load file and pipe it to user, return true is required to bypass default download option
    const readStream = fs.createReadStream(fileRef.versions[version].path);
    readStream.on("error", (err) => {
      throw err;
    });
    readStream.pipe(http.response);

    return true;
  },
});
```
function namingFunction(file) {
  let name = file.name.split(".")[0];
  return `${name
    .replace(/ /g, "_")
    .replace(/[^A-Za-z0-9_-]/gi, "_")}_${+new Date()}`;
}
```

I would expect `file.link()` to return a link that included the renamed file OR even the original name but it's the _id eg. `http://localhost/cdn/storage/uploadedDocumentFiles/Q8iG7KX3zpqwos3gY/original/Q8iG7KX3zpqwos3gY.pdf`

**Comment by dr-dimitru** [comment] 2020-10-13 12:07
> The intecept download doesn't seem to do much - also it only runs sometimes for some reason?!

Because browser won't request file from server, it would cache it.

> I would expect file.link() to return a link that included the renamed file OR even the original name

This is not possible in the current implementation. To set __name__ (*not URL*) of downloaded file use `Content-Disposition` header. To set header use [`. responseHeaders()` hook](https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/custom-response-headers.md#custom-response-headers)

Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment] 2020-10-22 00:29
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Closed by dr-dimitru** 2020-10-22 00:29 UTC
Labels: question

**Comment by blockracers** [comment] 2020-10-22 00:34
Sorry for the radio silence - I used your suggestion of response headers and that worked for me - thanks :)

**Comment by dr-dimitru** [comment] 2020-10-22 01:05
@blockracers I'm glad it worked for you 👍

Please support this project with:
 - [Become a sponsor on GitHub](https://github.com/sponsors/dr-dimitru/dashboard) and GitHub __would double your every contribution__ during next 12 months!;
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Star this package on GitHub;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).
