### ISSUE TITLE
How to backup Images into new collection?

### ISSUE THREAD

**Issue by Nilsalunkhe** [VeliovGroup/Meteor-Files#575] opened 2018-02-13 05:04 UTC
I have few images in collection of Images. I want to backup that images into new collection.
but there is one issue that is when I'm inserting all records into new collection path of original images is changing. And i'm not able to get images on new path.

Here is My code: 
```js
var images = Images.collection.find({}).fetch();
        for (let i = 0; i< images.length; i++) {
            delete images[i]["_id"];
            HistoryImages.insert(images[i]);
        }
```

Is this is a right way to doing this? or is there another way to take  backup of images and store in new collection? Please help me to resolve this issue.

**Comment by mksh-su** [comment] 2018-02-13 19:53
Hello @Nilsalunkhe ,

Do you use the latest versions of Meteor and Meteor-Files? Also, do you get any error when running your code?

/cc @dr-dimitru

**Comment by Nilsalunkhe** [comment] 2018-02-14 04:53
Hi @mksh-su ,
Yes I'm using latest version of Meteor and Meteor-Files. 
No errors while running code

**Comment by mksh-su** [comment] 2018-02-15 08:12
Hi @Nilsalunkhe ,

You may take a look at our [demos](https://github.com/VeliovGroup/Meteor-Files-Demos), some of them use image collections. You may find an example of using more than one collection [here](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo-simplest-streaming/lib/files.collections.js).
I believe that these examples may help you in solving this issue. If they don't, let us know about it.

**Comment by dr-dimitru** [comment] 2018-02-25 13:41
Hello @Nilsalunkhe ,

Sorry for late reply, you should use [`.addFile()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/addFile):

```js
var images = Images.collection.find({}).fetch();
for (let i = 0; i< images.length; i++) {
   HistoryImages.addFile(images[i].path, {
      fileName: images[i].name,
      type: images[i].type,
      fileId: images[i]._id, // <--- If you wish to keep same ID, which is used in download path generation
      meta: images[i].meta
   });
}
```

Feel free to close it in case if the issue is solved on your end.

**Comment by Nilsalunkhe** [comment] 2018-02-26 04:04
@dr-dimitru thanks for reply. I have resolved the issue.

**Comment by mksh-su** [comment] 2018-02-26 08:05
Hey @Nilsalunkhe ,

If you like the project, please, support it by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)

**Closed** 2018-02-26 08:05 UTC
Labels: question
