### ISSUE TITLE
Deploy error with v1.7.16

### ISSUE THREAD

**Issue by marcoschwartz** [VeliovGroup/Meteor-Files#420] opened 2017-05-20 10:37 UTC
Hello,

Since v1.7.16, I have this error when I am trying to deploy my app to my Digital Ocean server with MUP:

Error: Can't find npm module 'fs-extra'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package?
	    at Object.require (/bundle/bundle/programs/server/boot.js:200:17)
	    at meteorInstall.node_modules.meteor.ostrio:files.files.coffee.js (/bundle/bundle/programs/server/packages/ostrio_files.js:48:12)
	    at fileEvaluate (packages/modules-runtime.js:197:9)
	    at require (packages/modules-runtime.js:120:16)
	    at /bundle/bundle/programs/server/packages/ostrio_files.js:4072:15
	    at /bundle/bundle/programs/server/packages/ostrio_files.js:4083:3
	    at /bundle/bundle/programs/server/boot.js:303:34
	    at Array.forEach (native)
	    at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
	    at /bundle/bundle/programs/server/boot.js:128:5

I added fs-extra to my app, it is in my package.json file, and also locally I have no issues, it's only when I deploy my app to my live server. I have other NPM packages that don't pose any issue. Any idea how to fix that? Thanks!

**Comment by paulincai** [comment] 2017-05-20 10:38
Me too on Heroku

**Comment by paulincai** [comment] 2017-05-20 13:39
@marcoschwartz the issue is probably due to the change below, I am not sure what was @dr-dimitru  intention, probably to lock the NPMs on particular versions bundled with the Meteor package and not versions of the packages.js. Let's see what he says

![screen shot 2017-05-20 at 17 36 27](https://cloud.githubusercontent.com/assets/26188915/26276179/31a9df78-3d83-11e7-8509-32ceaa032e69.png)

**Comment by dr-dimitru** [comment] 2017-05-20 14:07
Hello @marcoschwartz , @paulincai ,

This is fix for more ugly error described in [#417](https://github.com/VeliovGroup/Meteor-Files/issues/417). Please check #417 thread.

I believe it can be fixed with:
```shell
meteor npm install fs-extra --save
```

Let me know if it works for you

**Comment by paulincai** [comment] 2017-05-20 14:54
@dr-dimitru @marcoschwartz tried that, even took it to Heroku although I knew nothing was going to change but just to make sure that I don't have to lie to you :).

Your suggestion only works locally where you avail of the meteor commands but you cannot do that on Heroku. So if I run 'meteor npm.....' when I deploy to Heroku I still deploy the same thing as before, namely the unchanged package.json file. So it doesn't work. I tried a prayer too and invoked some mythological deities

**Comment by dr-dimitru** [comment] 2017-05-20 15:19
1. Why `package.json` is unchanged, have you forgot `--save` flag?
 2. Do you run `meteor build` before deploy to Heroku?

**Comment by paulincai** [comment] 2017-05-20 15:32
- I had 'fs-extras' installed without meteor before the npm command and with --save so I could see it under dependencies in packages.json. I uninstalled with --save and installed with meteor npm install fs-extra --save so it added back to packages.json under dependecies....so no change to the repo. Heroku installs the package cause I can see it in the code but I think your main js files calles the package with Npm.require('fs-extra') instead of simply require('fs-extra') and us and Digital Ocean doesn't interpret that...I'm thinking.

- Heroku does the build, I only push to master. See below (https://github.com/AdmitHub/meteor-buildpack-horse.git#beta) :
![screen shot 2017-05-20 at 19 25 59](https://cloud.githubusercontent.com/assets/26188915/26276889/40c5361a-3d92-11e7-968c-4075b76a4506.png)

**Comment by paulincai** [comment] 2017-05-20 15:39
@dr-dimitru  replying your message in the other issue conversation:

Really don't know what to say. I deleted my box twice and rebuild new. Code works on local but not on Heroku

**Error:** Can't find npm module 'fs-extra'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package? 
**May 20 08:01:17 app app/web.1: at Object.require** (/app/.meteor/heroku_build/app/programs/server/boot.js:200:17) 
**May 20 08:01:17 app app/web.1:**  at meteorInstall.node_modules.meteor.ostrio:files.files.coffee.js (packages/ostrio_files/files.coffee:8:18) 
**May 20 08:01:17 app app/web.1:**    at fileEvaluate (packages/modules-runtime.js:197:9) 
**May 20 08:01:17 app/web.1:**    at require (packages/modules-runtime.js:120:16) 
**May 20 08:01:17 app app/web.1:**      at /app/.meteor/heroku_build/app/programs/server/packages/ostrio_files.js:4388:15 
**May 20 08:01:17 app/web.1:**      at /app/.meteor/heroku_build/app/programs/server/packages/ostrio_files.js:4399:3 
**May 20 08:01:17 app/web.1:**      at /app/.meteor/heroku_build/app/programs/server/boot.js:303:34 
**May 20 08:01:17 app/web.1:**      at Array.forEach (native) 
**May 20 08:01:17 app/web.1:**      at Function._.each._.forEach (/app/.meteor/heroku_build/app/programs/server/node_modules/underscore/underscore.js:79:11) 
**May 20 08:01:17 app/web.1:**      at /app/.meteor/heroku_build/app/programs/server/boot.js:128:5

**Comment by dr-dimitru** [comment] 2017-05-20 15:41
1. I recommend to try build it yourself and deploy (to make sure there is no error in a meteor-horse), [see this repo](https://github.com/VeliovGroup/Meteor-Files-Demos/tree/master/demo) for examples and instructions
 2. Make sure Heroku installs NPM packages with `"preinstall": "cd ./programs/server && npm install",`, [see here](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/package.json#L7)
 3. Make sure NPM and Node has appropriate versions, [see example here](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/package.json#L62)

**Comment by dr-dimitru** [comment] 2017-05-20 15:44
Have you tried steps from #417 ?
Especially [this one](https://github.com/VeliovGroup/Meteor-Files/issues/417#issuecomment-302757752) ?

**Comment by dr-dimitru** [comment] 2017-05-20 15:46
Have you tried to install packages mentioned in [this diff](https://www.diffchecker.com/0C7iliA2) ?

**Comment by marcoschwartz** [comment] 2017-05-20 17:08
I tried all the suggestions above, still the same error while trying to deploy with MUP, locally the app still works perfectly fine.

**Comment by dr-dimitru** [comment] 2017-05-20 17:16
Can't say much about MUP.
 - Does it worked before v1.7.16? If so, what version was it?
 - Here is [example how to deploy without MUP](https://gist.github.com/dr-dimitru/ed7b0cc77ea627a06c9af1f791699eda)

**Comment by marcoschwartz** [comment] 2017-05-20 17:38
Yes, worked last night with 1.7.15 :)

**Comment by dr-dimitru** [comment] 2017-05-20 20:13
@macrozone could you please try with adding next two lines to `package.json`:
```json
{
  "dependencies": {
    "meteor-deque": "*",
    "meteor-node-stubs": "^0.2.5"
  }
}
```

And then run:
```shell
meteor npm install --save
```

**Comment by marcoschwartz** [comment] 2017-05-20 20:21
I just tried that, it resulted in the same error. Sure thing, here is my package.json dependencies:

"dependencies": {
    "aws-sdk": "^2.54.0",
    "babel-runtime": "*",
    "bcrypt": "*",
    "chart.js": "^2.5.0",
    "cheerio": "*",
    "file-type": "^4.3.0",
    "fs-extra": "^3.0.1",
    "html-minifier": "^3.3.3",
    "jsmediatags": "*",
    "meteor-node-stubs": "^0.2.5",
    "meteor-deque": "*",
    "throttle": "^1.0.3"
  },

**Comment by dr-dimitru** [comment] 2017-05-20 20:33
@marcoschwartz is it okay to have `babel-runtime`, `bcrypt` and other packages without version? (*I'm just curious*), or you have removed it before posting on purpose?

Anyways I'm suggesting to:
 1. Remove and add back Meteor Files package `meteor remove ostrio:files; meteor add ostrio:files`;
 2. If it wouldn't help, see steps below.
-----
 1. Add all packages from [this diff](https://www.diffchecker.com/GN0SS82W) right to the `package.json` (*with packages versions*);
 2. Remove `./node_modules`;
 3. Run `meteor reset` (*if possible, as __this will drop local MongoDB__*);
 4. Run `meteor npm install --save`.

I'm pretty sure you will end up [with same results as in 417](https://github.com/VeliovGroup/Meteor-Files/issues/417#issuecomment-302780110).

**Comment by paulincai** [comment] 2017-05-20 23:20
@dr-dimitru I tried everything that you suggested. Everything. Unfortunately nothing worked and it is already far too much wasted in troubleshooting. 

I had to go a separate way and built a local package with the only amendment that I am doing require('package') instead Npm.require('package'). All ok now and I will move on for the time being.

**Comment by dr-dimitru** [comment] 2017-05-21 01:39
@paulincai thanks a lot for tests, I guess I'll move package to ES6 and `imports` for the 1.8 (*should be the next release*), to solve those annoying errors, btw, is this happens for you use [one click install](https://heroku.com/deploy?template=https://github.com/VeliovGroup/Meteor-Files-Demo) with [demo app](https://github.com/VeliovGroup/Meteor-Files-Demos/tree/master/demo).

It uses v1.7.16, and works like a charm on my end, it's actually the https://files.veliov.com

**Comment by paulincai** [comment] 2017-05-21 01:49
@dr-dimitru The one click install is a no-go for me. I need to get it through the repository. It is impossible to manage development and pipelines with multiple developers if you don't do everything through the repo (git). Secondly, I cannot do local builds (time wise), I am pushing to Master(auto to Heroku) 15-20 times a day and make sure things are right for the testing mobiles which are connected 'live'. Each deploy takes 6 minutes and need to get some people in my team and need to have structure in place to make their onboarding easy. So, I know you wanted to know if that routine worked but unfortunately I didn't try it.

**Comment by dr-dimitru** [comment] 2017-05-21 02:30
> The one click install is a no-go for me. I need to get it through the repository. It is impossible to manage development and pipelines with multiple developers if you don't do everything through the repo (git).

I meant to try it for the test reasons.

> So, I know you wanted to know if that routine worked but unfortunately I didn't try it.

Ok

**Comment by marcoschwartz** [comment] 2017-05-21 06:45
I also just tried all the steps proposed by @dr-dimitru , still the same error. Therefore for now I'll stick to 1.7.15 & wait for the 1.8 release as you said :)

**Comment by alexgzhou** [comment] 2017-05-22 15:52
Can't find npm module 'file-type'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package?

**Comment by dr-dimitru** [comment] 2017-05-22 16:12
@alexgzhou have you seen #417 ?

```shell
meteor npm install --save file-type
```

Or downgrade to v1.7.15
```shell
meteor remove ostrio:files
meteor add ostrio:files@1.7.15
```

**Comment by alexgzhou** [comment] 2017-05-22 16:20
@dr-dimitru v1.7.13 works for me, when i upgrade to v1.7.15 yesterday, i have the error of Can't find npm module 'throttle'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package? 
so i downgrade to 1.7.13, and just before i saw 1.7.16 was published, i thought the problem maybe solved, but with no luck~
I will type your tips and feedback soon~

**Comment by alexgzhou** [comment] 2017-05-22 16:23
@dr-dimitru solved~~~

**Comment by alexgzhou** [comment] 2017-05-22 16:27
@dr-dimitru solved~~~ with `meteor npm install --save file-type`

**Comment by dr-dimitru** [comment] 2017-05-22 16:28
@alexgzhou great.

**Comment by alexgzhou** [comment] 2017-05-22 16:40
@dr-dimitru My projects do rely on your wonderful works, thank you~

**Comment by dr-dimitru** [comment] 2017-05-22 16:48
@alexgzhou Appreciated, this means a lot to me.

**Comment by edwinmp** [comment] 2017-05-22 22:29
Getting the same error while running unit tests with the `practicalmeteor:mocha` package.
Neither `meteor npm install --save fs-extra` nor downgrading to version 1.7.15 has worked.

**Comment by dr-dimitru** [comment] 2017-05-22 22:36
@edwinmp thank you for info, I'll wait for [v1.4.4.3](https://github.com/meteor/meteor/pull/8711/files), there is minor changes to isobuild, idk if it's related, but hope it will be fixed.

Anyways it's weird, as you can see at this thread and #417 .
Everyone has it's own solution, for someone only `v1.7.13` is works, for others `v1.7.14`, for you `v1.7.15`. Many other users reported installing missed NPM package solves issue only locally...

**Comment by marcoschwartz** [comment] 2017-05-29 08:43
I can confirm that the problem is still present with v.1.7.16 & Meteor 1.4.4.3, just tried it at the moment. So for now reverted again to v.1.7.15

**Comment by sotarules** [comment] 2017-06-01 00:31
+1 I'm seeing this on 1.5

**Comment by sotarules** [comment] 2017-06-01 00:37
Yes, I just tried two commands:

```
meteor npm install --save fs-extra
meteor npm install --save file-type
```
This seems to have fixed it.  Right now I'm running 1.7.15.

**Comment by dr-dimitru** [comment] 2017-06-01 00:39
@sotarules thanks a lot

**Comment by pozylon** [comment] 2017-06-01 20:26
Adding fs-extra and file-type only helps locally but will not help if meteor build is used...

**Comment by sotarules** [comment] 2017-06-01 21:45
I can confirm what @pozylon has stated, namely that adding fs-extra and file-type manually with meteor npm only helps the development environment.  When attempting to run a bundle in production, the system throws the same errors as reported earlier:

```
/home/ubuntu/bundles/sherpa/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Can't find npm module 'fs-extra'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package?
    at Object.require (/home/ubuntu/bundles/sherpa/bundle/programs/server/boot.js:230:17)
    at meteorInstall.node_modules.meteor.ostrio:files.files.coffee.js (packages/ostrio_files/files.coffee:8:18)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at /home/ubuntu/bundles/sherpa/bundle/programs/server/packages/ostrio_files.js:4394:15
    at /home/ubuntu/bundles/sherpa/bundle/programs/server/packages/ostrio_files.js:4405:3
    at /home/ubuntu/bundles/sherpa/bundle/programs/server/boot.js:338:34
    at Array.forEach (native)
    at Function._.each._.forEach (/home/ubuntu/bundles/sherpa/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /home/ubuntu/bundles/sherpa/bundle/programs/server/boot.js:158:5
```

**Comment by dr-dimitru** [comment] 2017-06-01 21:50
@sotarules thank you for update. Could you in terms of testing try [`cd ./programs/server && npm install`](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/package.json#L7)

**Comment by sotarules** [comment] 2017-06-01 21:56
@dr-dimitru I tried this:

```
ubuntu@v-as-sherpa:~/bundles/sherpa/bundle$ cd programs/server
ubuntu@v-as-sherpa:~/bundles/sherpa/bundle/programs/server$ sudo npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/home/ubuntu/bundles/sherpa/bundle/programs/server)
ubuntu@v-as-sherpa:~/bundles/sherpa/bundle/programs/server$
```
Not sure if that worked correctly as you had expected, but after doing that and restarting, I'm still getting this:
```
/home/ubuntu/bundles/sherpa/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Can't find npm module 'fs-extra'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package?
    at Object.require (/home/ubuntu/bundles/sherpa/bundle/programs/server/boot.js:230:17)
    at meteorInstall.node_modules.meteor.ostrio:files.files.coffee.js (packages/ostrio_files/files.coffee:8:18)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at /home/ubuntu/bundles/sherpa/bundle/programs/server/packages/ostrio_files.js:4394:15
    at /home/ubuntu/bundles/sherpa/bundle/programs/server/packages/ostrio_files.js:4405:3
    at /home/ubuntu/bundles/sherpa/bundle/programs/server/boot.js:338:34
    at Array.forEach (native)
    at Function._.each._.forEach (/home/ubuntu/bundles/sherpa/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /home/ubuntu/bundles/sherpa/bundle/programs/server/boot.js:158:5
```

**Comment by sotarules** [comment] 2017-06-01 22:08
FYI for others watching this thread, I tried removing **fs-extra** and **file-type** and then tried:

1.7.13
1.7.14
1.7.15
1.7.16

In all cases, I got this in the development environment:

```
W20170601-15:03:57.983(-7)? (STDERR) C:\git\ten\website\incentive-sherpa\.meteor\local\build\programs\server\node_modules\fibers\future.js:280
W20170601-15:03:58.046(-7)? (STDERR)                                            throw(ex);
W20170601-15:03:58.048(-7)? (STDERR)                                            ^
W20170601-15:03:58.049(-7)? (STDERR)
W20170601-15:03:58.051(-7)? (STDERR) Error: Can't find npm module 'fs-extra'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package?
W20170601-15:03:58.052(-7)? (STDERR)     at Object.require (C:\git\ten\website\incentive-sherpa\.meteor\local\build\programs\server\boot.js:230:17)
W20170601-15:03:58.053(-7)? (STDERR)     at meteorInstall.node_modules.meteor.ostrio:files.files.coffee.js (packages/ostrio_files/files.coffee:8:18)
W20170601-15:03:58.054(-7)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:333:9)
W20170601-15:03:58.055(-7)? (STDERR)     at require (packages\modules-runtime.js:228:16)
W20170601-15:03:58.055(-7)? (STDERR)     at C:\git\ten\website\incentive-sherpa\.meteor\local\build\programs\server\packages\ostrio_files.js:4394:15
W20170601-15:03:58.056(-7)? (STDERR)     at C:\git\ten\website\incentive-sherpa\.meteor\local\build\programs\server\packages\ostrio_files.js:4405:3
W20170601-15:03:58.057(-7)? (STDERR)     at C:\git\ten\website\incentive-sherpa\.meteor\local\build\programs\server\boot.js:338:34
W20170601-15:03:58.058(-7)? (STDERR)     at Array.forEach (native)
W20170601-15:03:58.059(-7)? (STDERR)     at Function._.each._.forEach (C:\git\ten\website\incentive-sherpa\.meteor\local\build\programs\server\node_modules\underscore\underscore.js:79:11)
W20170601-15:03:58.060(-7)? (STDERR)     at C:\git\ten\website\incentive-sherpa\.meteor\local\build\programs\server\boot.js:158:5
=> Exited with code: 1
```
I should clarify that I'm using Windows 7 to develop and build (then install on Ubuntu 16.04).  Not sure if this is a consideration).

**Comment by dr-dimitru** [comment] 2017-06-01 22:13
> I should clarify that I'm using Windows 7 to develop and build (then install on Ubuntu 16.04). Not sure if this is a consideration.

Do you use any build flags?

**Comment by dr-dimitru** [comment] 2017-06-01 22:16
Hmm... I have a bit [different results](https://github.com/meteor/meteor/issues/8708#issuecomment-304091905)

**Comment by ankibalyan** [comment] 2017-06-01 22:36
same issue, fixed on local with following, but error is still coming on production site at Aws.
```
meteor npm install --save fs-extra
meteor npm install --save file-type
```

**Comment by ankibalyan** [comment] 2017-06-01 22:37
There some that this package has to update, so many people are facing this issue only with this package.

**Comment by dr-dimitru** [comment] 2017-06-01 22:40
> There is something with this package, that has to be update, many people are facing same issue only with this package.

That's true, we're working on the major update.

**Comment by sotarules** [comment] 2017-06-01 22:41
@dr-dimitru here is my build script:

```
@echo off
c:
cd \git\ten\website\incentive-sherpa
del \bundles\incentive-sherpa.tar.gz
meteor build \bundles --architecture os.linux.x86_64
```
So you see, I do add one flag, namely the **architecture** of the deployment machine.

**Comment by sotarules** [comment] 2017-06-01 22:43
@dr-dimitru not sure if this is relevant but I should stress that I'm trying this on **Meteor 1.5** (bleeding edge).

**Comment by dr-dimitru** [comment] 2017-06-01 22:46
@ankibalyan @sotarules is the downgrading to `1.7.13` solve this issue?

**Comment by sotarules** [comment] 2017-06-01 22:48
@dr-dimitru no this is what I got:

```
C:\git\ten\website\incentive-sherpa>**meteor add ostrio:files@1.7.13**
Currently using ostrio:files with version constraint 1.7.15.
The version constraint will be changed to 1.7.13.

ostrio:files: File upload via DDP/HTTP to server FS, AWS, GridFS, DropBox, Google Drive or other 3rd party storage

C:\git\ten\website\incentive-sherpa>**sherpa**
[[[[[ C:\git\ten\website\incentive-sherpa ]]]]]

=> Started proxy.
W20170601-15:01:38.469(-7)? (STDERR) C:\Users\David\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20170601-15:01:38.828(-7)? (STDERR)                                            throw(ex);
W20170601-15:01:38.829(-7)? (STDERR)                                            ^
W20170601-15:01:38.830(-7)? (STDERR)
W20170601-15:01:38.831(-7)? (STDERR) Error: Can't find npm module 'fs-extra'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package?
W20170601-15:01:38.832(-7)? (STDERR)     at Object.require (C:\git\ten\website\incentive-sherpa\.meteor\local\build\programs\server\boot.js:230:17)
W20170601-15:01:38.833(-7)? (STDERR)     at meteorInstall.node_modules.meteor.ostrio:files.files.coffee.js (packages/ostrio_files/files.coffee:8:18)
W20170601-15:01:38.833(-7)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:333:9)
W20170601-15:01:38.834(-7)? (STDERR)     at require (packages\modules-runtime.js:228:16)
W20170601-15:01:38.835(-7)? (STDERR)     at C:\git\ten\website\incentive-sherpa\.meteor\local\build\programs\server\packages\ostrio_files.js:4394:15
W20170601-15:01:38.836(-7)? (STDERR)     at C:\git\ten\website\incentive-sherpa\.meteor\local\build\programs\server\packages\ostrio_files.js:4405:3
W20170601-15:01:38.837(-7)? (STDERR)     at C:\git\ten\website\incentive-sherpa\.meteor\local\build\programs\server\boot.js:338:34
W20170601-15:01:38.838(-7)? (STDERR)     at Array.forEach (native)
W20170601-15:01:38.839(-7)? (STDERR)     at Function._.each._.forEach (C:\Users\David\AppData\Local\.meteor\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20170601-15:01:38.840(-7)? (STDERR)     at C:\git\ten\website\incentive-sherpa\.meteor\local\build\programs\server\boot.js:158:5
=> Exited with code: 1
```

**Comment by mgscreativa** [comment] 2017-06-01 23:08
Got it working with meteor **npm install --save file-type fs-extra**

ostrio:files v1.7.16
Meteor v1.5

**Comment by ankibalyan** [comment] 2017-06-01 23:34
no luck, I've deployed with docker, circleCI, and using pm2.

```
0|main     | Error: Can't find npm module 'fs-extra'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package?
0|main     |     at Object.require (/app/bundle/programs/server/boot.js:230:17)
0|main     |     at meteorInstall.node_modules.meteor.ostrio:files.files.coffee.js (packages/ostrio_files/files.coffee:8:18)
0|main     |     at fileEvaluate (packages/modules-runtime.js:333:9)
0|main     |     at require (packages/modules-runtime.js:228:16)
0|main     |     at /app/bundle/programs/server/packages/ostrio_files.js:4394:15
0|main     |     at /app/bundle/programs/server/packages/ostrio_files.js:4405:3
0|main     |     at /app/bundle/programs/server/boot.js:338:34
0|main     |     at Array.forEach (native)
0|main     |     at Function._.each._.forEach (/app/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
0|main     |     at /app/bundle/programs/server/boot.js:158:5

```

**Comment by sotarules** [comment] 2017-06-01 23:39
@ankibalyan I'm getting the same symptom when deploying on my own VMWare Ubuntu 16.04.

The bundle installation process works fine, but when I try to **start** my Meteor cluster, I get the same message you posted above, in each of my **.forever** log files.

**Comment by ankibalyan** [comment] 2017-06-01 23:53
> Got it working with meteor npm install --save file-type fs-extra
ostrio:files v1.7.16
Meteor v1.5

@mgscreativa yes it does works only in development mode, from my local machine, but It is getting failed when we are trying to deploy, using `meteor build` && then `cd /app/bundle/programs/server && npm install && npm cache clear`.

**Comment by ankibalyan** [comment] 2017-06-02 00:06
It just worked for now :dagger: On my server I dig into my docker image and then ran 
`cd /app/bundle/programs/server && npm install --save file-type fs-extra`, then restarted `pm2 restart main`.

@sotarules If you can try something similar It may work for now. but it has to be fixed.

**Comment by dr-dimitru** [comment] 2017-06-02 01:23
Hello everyone, thanks a lot for investigation and reports, we haven't found a cause for this issue, but hopefully found a solution to finally fix this. Please update to [`v1.7.17`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.17) and let me know how it work for you

**Comment by sotarules** [comment] 2017-06-02 01:47
@dr-dimitru thanks so much for fixing this so quickly.  I can confirm that 1.7.17 fixes both development and production environments.  Once 1.7.17 is in play, there is no need to add npm packages file-type nor fs-extra.

**Comment by dr-dimitru** [comment] 2017-06-02 01:50
Great news @sotarules , thank you for update.
Hope it will work for all of us

**Comment by ankibalyan** [comment] 2017-06-02 06:42
@dr-dimitru Yes, It works like a charm. Thanks a lot for that quick release. :hamburger:

**Comment by pozylon** [comment] 2017-06-02 06:58
@dr-dimitru Thank you so much for fixing it! This package is absolutely awesome btw!

**Comment by dr-dimitru** [comment] 2017-06-02 07:02
@ankibalyan @pozylon Thank you guys 👨‍💻

**Comment by marcoschwartz** [comment] 2017-06-02 07:14
Works for all our production apps as well, thanks @dr-dimitru for the excellent work!

**Comment by valorloff** [comment] 2017-06-04 13:51
Hi!
```
 Error: Can't find npm module 'file-type'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package?
Error: Can't find npm module 'fs-extra'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package?
```
in dev mode treated successfully by
`meteor npm install --save file-type fs-extra`
but after deploying error appeared again, and I had to do the same 
```
meteor npm install --save file-type
meteor npm install --save fs-extra
```
on the hosting server, how to cure it permanently ?

**Comment by sotarules** [comment] 2017-06-04 15:35
@valorloff version 1.7.17 has been confirmed to fix the issue.  Change directory into your Meteor project folder and do this:

`meteor add ostrio:files@1.7.17`

And it should cure it completely, both for development and on your hosting server.

**Comment by dr-dimitru** [comment] 2017-06-04 17:19
@valorloff feel free to `meteor npm remove --save file-type fs-extra` if you don't use it in your app directly. And make sure you're on the latest release. In case it won't fix run:
First try:
```shell
meteor remove ostrio:files
meteor add ostrio:files
```

If remove/add doesn't help:
```shell
rm -Rf ./node_modules
meteor reset # <- ! Caution: will drop local mongo db
meteor npm install --save
meteor update
```

**Comment by valorloff** [comment] 2017-06-05 05:23
@dr-dimitru As always, it worked!
Thanks!

**Comment by dr-dimitru** [comment] 2017-06-09 01:04
Thank you everyone. Seems like it's fixed for all of us. Going to close it.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made

**Closed by dr-dimitru** 2017-06-09 01:04 UTC
Labels: In a case of the fire - Read This, question

**Comment by valorloff** [comment] 2017-08-04 09:46
Hi!
after refactoring app to react:
```
Exception from Tracker recompute function:
meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:942 TypeError: this._debug is not a function
    at module.runModuleSetters.FilesCollectionCore.link (ostrio_files.js?hash=3a35370b63efe4dbb13a6152206c2a5383101832:1358)
    at FilesCollection.Images.link (collections.js:44)
    at FileCursor.module.runModuleSetters.FileCursor.link (ostrio_files.js?hash=3a35370b63efe4dbb13a6152206c2a5383101832:1445)
    at Product.imageFile (product.jsx:29)
    at Product.render (product.jsx:45)
    at modules.js?hash=38670f4eb4440e3943dd829ee8146bc073e26707:60106
    at measureLifeCyclePerf (modules.js?hash=38670f4eb4440e3943dd829ee8146bc073e26707:59386)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (modules.js?hash=38670f4eb4440e3943dd829ee8146bc073e26707:60105)
    at ReactCompositeComponentWrapper._renderValidatedComponent (modules.js?hash=38670f4eb4440e3943dd829ee8146bc073e26707:60132)
    at ReactCompositeComponentWrapper.performInitialMount (modules.js?hash=38670f4eb4440e3943dd829ee8146bc073e26707:59672)
```
```
npm remove/install --save file-type fs-extra
meteor remove ostrio:files
meteor add ostrio:files
```
and
```
rm -Rf ./node_modules
meteor reset # <- ! Caution: will drop local mongo db
meteor npm install --save
meteor update
```
does not help (:

**Comment by dr-dimitru** [comment] 2017-08-04 12:04
Hello @valorloff ,

Looks like potential bug.
Could you move it to separate ticket please?

**Comment by valorloff** [comment] 2017-08-04 12:07
sorry, just minute

**Comment by dr-dimitru** [comment] 2017-08-04 12:08
Took a look on your code once again, you are lost the method context, use this to fix:
```js
const _origLink = Images.link;
Images.link = function (v) {
  return _origLink.call(Images, v).replace(__meteor_runtime_config__.ROOT_URL, 'xxxxxxxxx/');
};
```

OR:
```js
const _origLink = Images.link.bind(Images);
Images.link = (v)=> {
  return _origLink(v).replace(__meteor_runtime_config__.ROOT_URL, 'xxxxxxxxx/');
};
```
