### ISSUE TITLE
Extreme slow uploads (DDP/HTTP)

### ISSUE THREAD

**Issue by michael-trinity** [veliovgroup/Meteor-Files#787] opened 2021-02-12 11:06 UTC
### I'm having an issue:
  - Trying to upload a 100KB image takes 2 minutes
  - v2.0.0
  - Meteor 2
  -Server is on Ubuntu in a VM, client is Windows

```
I20210212-19:58:14.775(9)? [FilesCollection.storagePath] Set to: assets/app/uploads/Images
=> Meteor server restarted
I20210212-19:58:15.073(9)? [FilesCollection] [find({}, undefined)]
I20210212-19:58:15.104(9)? [FilesCollection] [find({}, undefined)]
I20210212-19:58:15.718(9)? [FilesCollection] [find({}, undefined)]
I20210212-19:58:15.759(9)? [FilesCollection] [find({}, undefined)]
I20210212-20:00:06.816(9)? [FilesCollection] [File Start Method] 20210125_214710.jpg - S7QeJwCJWyELFhXKc
I20210212-20:00:06.817(9)? [FilesCollection] [Upload] [DDP Start Method] Got #-1/10 chunks, dst: 20210125_214710.jpg
=> Client modified -- refreshing
I20210212-20:01:31.576(9)? [FilesCollection] [File Start HTTP] 20210125_214710.jpg - DB4HrwpYicdhyKXvN
I20210212-20:01:31.578(9)? [FilesCollection] [Upload] [HTTP Start Method] Got #-1/20 chunks, dst: 20210125_214710.jpg
I20210212-20:02:20.911(9)? [FilesCollection] [Upload] [HTTP] Got #1/20 chunks, dst: 20210125_214710.jpg
W20210212-20:02:45.556(9)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: Socket {
W20210212-20:02:45.560(9)? (STDERR)   connecting: false,
W20210212-20:02:45.561(9)? (STDERR)   _hadError: false,
W20210212-20:02:45.561(9)? (STDERR)   _parent: null,
W20210212-20:02:45.561(9)? (STDERR)   _host: null,
W20210212-20:02:45.561(9)? (STDERR)   _readableState: ReadableState {
W20210212-20:02:45.561(9)? (STDERR)     objectMode: false,
W20210212-20:02:45.561(9)? (STDERR)     highWaterMark: 16384,
W20210212-20:02:45.561(9)? (STDERR)     buffer: BufferList { head: null, tail: null, length: 0 },
W20210212-20:02:45.561(9)? (STDERR)     length: 0,
W20210212-20:02:45.561(9)? (STDERR)     pipes: null,
W20210212-20:02:45.562(9)? (STDERR)     pipesCount: 0,
W20210212-20:02:45.562(9)? (STDERR)     flowing: true,
W20210212-20:02:45.562(9)? (STDERR)     ended: false,
W20210212-20:02:45.562(9)? (STDERR)     endEmitted: false,
W20210212-20:02:45.562(9)? (STDERR)     reading: true,
W20210212-20:02:45.562(9)? (STDERR)     sync: false,
W20210212-20:02:45.562(9)? (STDERR)     needReadable: true,
W20210212-20:02:45.562(9)? (STDERR)     emittedReadable: false,
W20210212-20:02:45.562(9)? (STDERR)     readableListening: false,
W20210212-20:02:45.563(9)? (STDERR)     resumeScheduled: false,
W20210212-20:02:45.563(9)? (STDERR)     emitClose: false,
W20210212-20:02:45.563(9)? (STDERR)     autoDestroy: false,
W20210212-20:02:45.563(9)? (STDERR)     destroyed: false,
W20210212-20:02:45.564(9)? (STDERR)     defaultEncoding: 'utf8',
W20210212-20:02:45.564(9)? (STDERR)     awaitDrainWriters: null,
W20210212-20:02:45.564(9)? (STDERR)     multiAwaitDrain: false,
W20210212-20:02:45.564(9)? (STDERR)     readingMore: false,
W20210212-20:02:45.564(9)? (STDERR)     decoder: null,
W20210212-20:02:45.565(9)? (STDERR)     encoding: null,
W20210212-20:02:45.565(9)? (STDERR)     [Symbol(kPaused)]: false
W20210212-20:02:45.565(9)? (STDERR)   },
W20210212-20:02:45.565(9)? (STDERR)   readable: true,
W20210212-20:02:45.566(9)? (STDERR)   _events: [Object: null prototype] {
W20210212-20:02:45.566(9)? (STDERR)     end: [ [Function: onReadableStreamEnd], [Function: bound socketOnEnd] ],
W20210212-20:02:45.566(9)? (STDERR)     timeout: [Function: socketOnTimeout],
W20210212-20:02:45.566(9)? (STDERR)     data: [Function: bound socketOnData],
W20210212-20:02:45.566(9)? (STDERR)     error: [Function: socketOnError],
W20210212-20:02:45.567(9)? (STDERR)     close: [
W20210212-20:02:45.567(9)? (STDERR)       [Function: bound socketOnClose],
W20210212-20:02:45.567(9)? (STDERR)       [Function: onServerResponseClose]
W20210212-20:02:45.567(9)? (STDERR)     ],
W20210212-20:02:45.568(9)? (STDERR)     drain: [Function: bound socketOnDrain],
W20210212-20:02:45.568(9)? (STDERR)     resume: [Function: onSocketResume],
W20210212-20:02:45.568(9)? (STDERR)     pause: [Function: onSocketPause]
W20210212-20:02:45.568(9)? (STDERR)   },
W20210212-20:02:45.568(9)? (STDERR)   _eventsCount: 8,
W20210212-20:02:45.569(9)? (STDERR)   _maxListeners: undefined,
W20210212-20:02:45.569(9)? (STDERR)   _writableState: WritableState {
W20210212-20:02:45.569(9)? (STDERR)     objectMode: false,
W20210212-20:02:45.569(9)? (STDERR)     highWaterMark: 16384,
W20210212-20:02:45.570(9)? (STDERR)     finalCalled: false,
W20210212-20:02:45.570(9)? (STDERR)     needDrain: false,
W20210212-20:02:45.570(9)? (STDERR)     ending: false,
W20210212-20:02:45.570(9)? (STDERR)     ended: false,
W20210212-20:02:45.570(9)? (STDERR)     finished: false,
W20210212-20:02:45.571(9)? (STDERR)     destroyed: false,
W20210212-20:02:45.571(9)? (STDERR)     decodeStrings: false,
W20210212-20:02:45.571(9)? (STDERR)     defaultEncoding: 'utf8',
W20210212-20:02:45.571(9)? (STDERR)     length: 0,
W20210212-20:02:45.572(9)? (STDERR)     writing: false,
W20210212-20:02:45.572(9)? (STDERR)     corked: 0,
W20210212-20:02:45.573(9)? (STDERR)     sync: true,
W20210212-20:02:45.573(9)? (STDERR)     bufferProcessing: false,
W20210212-20:02:45.573(9)? (STDERR)     onwrite: [Function: bound onwrite],
W20210212-20:02:45.574(9)? (STDERR)     writecb: null,
W20210212-20:02:45.574(9)? (STDERR)     writelen: 0,
W20210212-20:02:45.574(9)? (STDERR)     afterWriteTickInfo: null,
W20210212-20:02:45.575(9)? (STDERR)     bufferedRequest: null,
W20210212-20:02:45.575(9)? (STDERR)     lastBufferedRequest: null,
W20210212-20:02:45.575(9)? (STDERR)     pendingcb: 0,
W20210212-20:02:45.575(9)? (STDERR)     prefinished: false,
W20210212-20:02:45.576(9)? (STDERR)     errorEmitted: false,
W20210212-20:02:45.576(9)? (STDERR)     emitClose: false,
W20210212-20:02:45.577(9)? (STDERR)     autoDestroy: false,
W20210212-20:02:45.577(9)? (STDERR)     bufferedRequestCount: 0,
W20210212-20:02:45.577(9)? (STDERR)     corkedRequestsFree: {
W20210212-20:02:45.577(9)? (STDERR)       next: null,
W20210212-20:02:45.577(9)? (STDERR)       entry: null,
W20210212-20:02:45.578(9)? (STDERR)       finish: [Function: bound onCorkedFinish]
W20210212-20:02:45.578(9)? (STDERR)     }
W20210212-20:02:45.578(9)? (STDERR)   },
W20210212-20:02:45.579(9)? (STDERR)   writable: true,
W20210212-20:02:45.579(9)? (STDERR)   allowHalfOpen: true,
W20210212-20:02:45.582(9)? (STDERR)   _sockname: null,
W20210212-20:02:45.582(9)? (STDERR)   _pendingData: null,
W20210212-20:02:45.582(9)? (STDERR)   _pendingEncoding: '',
W20210212-20:02:45.582(9)? (STDERR)   server: Server {
W20210212-20:02:45.582(9)? (STDERR)     insecureHTTPParser: undefined,
W20210212-20:02:45.584(9)? (STDERR)     _events: [Object: null prototype] {
W20210212-20:02:45.585(9)? (STDERR)       connection: [Function: connectionListener],
W20210212-20:02:45.586(9)? (STDERR)       clientError: [Function],
W20210212-20:02:45.586(9)? (STDERR)       request: [Function: newListener],
W20210212-20:02:45.588(9)? (STDERR)       upgrade: [Function: newListener]
W20210212-20:02:45.588(9)? (STDERR)     },
W20210212-20:02:45.589(9)? (STDERR)     _eventsCount: 4,
W20210212-20:02:45.589(9)? (STDERR)     _maxListeners: undefined,
W20210212-20:02:45.589(9)? (STDERR)     _connections: 7,
W20210212-20:02:45.590(9)? (STDERR)     _handle: TCP {
W20210212-20:02:45.590(9)? (STDERR)       reading: false,
W20210212-20:02:45.590(9)? (STDERR)       onconnection: [Function: onconnection],
W20210212-20:02:45.590(9)? (STDERR)       [Symbol(owner_symbol)]: [Circular]
W20210212-20:02:45.591(9)? (STDERR)     },
W20210212-20:02:45.591(9)? (STDERR)     _usingWorkers: false,
W20210212-20:02:45.591(9)? (STDERR)     _workers: [],
W20210212-20:02:45.591(9)? (STDERR)     _unref: false,
W20210212-20:02:45.592(9)? (STDERR)     allowHalfOpen: true,
W20210212-20:02:45.592(9)? (STDERR)     pauseOnConnect: false,
W20210212-20:02:45.592(9)? (STDERR)     httpAllowHalfOpen: false,
W20210212-20:02:45.592(9)? (STDERR)     timeout: 5000,
W20210212-20:02:45.593(9)? (STDERR)     keepAliveTimeout: 5000,
W20210212-20:02:45.593(9)? (STDERR)     maxHeadersCount: null,
W20210212-20:02:45.593(9)? (STDERR)     headersTimeout: 60000,
W20210212-20:02:45.593(9)? (STDERR)     _connectionKey: '4:0.0.0.0:24885',
W20210212-20:02:45.594(9)? (STDERR)     [Symbol(IncomingMessage)]: [Function: IncomingMessage],
W20210212-20:02:45.594(9)? (STDERR)     [Symbol(ServerResponse)]: [Function: ServerResponse],
W20210212-20:02:45.594(9)? (STDERR)     [Symbol(kCapture)]: false,
W20210212-20:02:45.594(9)? (STDERR)     [Symbol(asyncId)]: 143
W20210212-20:02:45.595(9)? (STDERR)   },
W20210212-20:02:45.595(9)? (STDERR)   _server: Server {
W20210212-20:02:45.595(9)? (STDERR)     insecureHTTPParser: undefined,
W20210212-20:02:45.595(9)? (STDERR)     _events: [Object: null prototype] {
W20210212-20:02:45.595(9)? (STDERR)       connection: [Function: connectionListener],
W20210212-20:02:45.596(9)? (STDERR)       clientError: [Function],
W20210212-20:02:45.596(9)? (STDERR)       request: [Function: newListener],
W20210212-20:02:45.596(9)? (STDERR)       upgrade: [Function: newListener]
W20210212-20:02:45.596(9)? (STDERR)     },
W20210212-20:02:45.597(9)? (STDERR)     _eventsCount: 4,
W20210212-20:02:45.597(9)? (STDERR)     _maxListeners: undefined,
W20210212-20:02:45.597(9)? (STDERR)     _connections: 7,
W20210212-20:02:45.597(9)? (STDERR)     _handle: TCP {
W20210212-20:02:45.597(9)? (STDERR)       reading: false,
W20210212-20:02:45.598(9)? (STDERR)       onconnection: [Function: onconnection],
W20210212-20:02:45.598(9)? (STDERR)       [Symbol(owner_symbol)]: [Circular]
W20210212-20:02:45.598(9)? (STDERR)     },
W20210212-20:02:45.598(9)? (STDERR)     _usingWorkers: false,
W20210212-20:02:45.599(9)? (STDERR)     _workers: [],
W20210212-20:02:45.599(9)? (STDERR)     _unref: false,
W20210212-20:02:45.599(9)? (STDERR)     allowHalfOpen: true,
W20210212-20:02:45.600(9)? (STDERR)     pauseOnConnect: false,
W20210212-20:02:45.600(9)? (STDERR)     httpAllowHalfOpen: false,
W20210212-20:02:45.601(9)? (STDERR)     timeout: 5000,
W20210212-20:02:45.601(9)? (STDERR)     keepAliveTimeout: 5000,
W20210212-20:02:45.602(9)? (STDERR)     maxHeadersCount: null,
W20210212-20:02:45.602(9)? (STDERR)     headersTimeout: 60000,
W20210212-20:02:45.603(9)? (STDERR)     _connectionKey: '4:0.0.0.0:24885',
W20210212-20:02:45.603(9)? (STDERR)     [Symbol(IncomingMessage)]: [Function: IncomingMessage],
W20210212-20:02:45.604(9)? (STDERR)     [Symbol(ServerResponse)]: [Function: ServerResponse],
W20210212-20:02:45.604(9)? (STDERR)     [Symbol(kCapture)]: false,
W20210212-20:02:45.605(9)? (STDERR)     [Symbol(asyncId)]: 143
W20210212-20:02:45.606(9)? (STDERR)   },
W20210212-20:02:45.607(9)? (STDERR)   timeout: 20000,
W20210212-20:02:45.607(9)? (STDERR)   parser: HTTPParser {
W20210212-20:02:45.608(9)? (STDERR)     '0': [Function: parserOnHeaders],
W20210212-20:02:45.608(9)? (STDERR)     '1': [Function: parserOnHeadersComplete],
W20210212-20:02:45.609(9)? (STDERR)     '2': [Function: parserOnBody],
W20210212-20:02:45.610(9)? (STDERR)     '3': [Function: parserOnMessageComplete],
W20210212-20:02:45.610(9)? (STDERR)     '4': [Function: bound onParserExecute],
W20210212-20:02:45.611(9)? (STDERR)     '5': [Function: bound onParserTimeout],
W20210212-20:02:45.611(9)? (STDERR)     _headers: [],
W20210212-20:02:45.612(9)? (STDERR)     _url: '',
W20210212-20:02:45.612(9)? (STDERR)     socket: [Circular],
W20210212-20:02:45.613(9)? (STDERR)     incoming: IncomingMessage {
W20210212-20:02:45.613(9)? (STDERR)       _readableState: [ReadableState],
W20210212-20:02:45.614(9)? (STDERR)       readable: true,
W20210212-20:02:45.614(9)? (STDERR)       _events: [Object: null prototype],
W20210212-20:02:45.615(9)? (STDERR)       _eventsCount: 3,
W20210212-20:02:45.616(9)? (STDERR)       _maxListeners: undefined,
W20210212-20:02:45.617(9)? (STDERR)       socket: [Circular],
W20210212-20:02:45.617(9)? (STDERR)       connection: [Circular],
W20210212-20:02:45.618(9)? (STDERR)       httpVersionMajor: 1,
W20210212-20:02:45.618(9)? (STDERR)       httpVersionMinor: 1,
W20210212-20:02:45.619(9)? (STDERR)       httpVersion: '1.1',
W20210212-20:02:45.621(9)? (STDERR)       complete: false,
W20210212-20:02:45.621(9)? (STDERR)       headers: [Object],
W20210212-20:02:45.622(9)? (STDERR)       rawHeaders: [Array],
W20210212-20:02:45.622(9)? (STDERR)       trailers: {},
W20210212-20:02:45.623(9)? (STDERR)       rawTrailers: [],
W20210212-20:02:45.624(9)? (STDERR)       aborted: false,
W20210212-20:02:45.624(9)? (STDERR)       upgrade: false,
W20210212-20:02:45.625(9)? (STDERR)       url: '/cdn/storage/Images/__upload',
W20210212-20:02:45.625(9)? (STDERR)       method: 'POST',
W20210212-20:02:45.626(9)? (STDERR)       statusCode: null,
W20210212-20:02:45.626(9)? (STDERR)       statusMessage: null,
W20210212-20:02:45.626(9)? (STDERR)       client: [Circular],
W20210212-20:02:45.627(9)? (STDERR)       _consuming: true,
W20210212-20:02:45.627(9)? (STDERR)       _dumped: false,
W20210212-20:02:45.628(9)? (STDERR)       originalUrl: '/cdn/storage/Images/__upload',
W20210212-20:02:45.629(9)? (STDERR)       _parsedUrl: [Url],
W20210212-20:02:45.629(9)? (STDERR)       secret: undefined,
W20210212-20:02:45.630(9)? (STDERR)       cookies: [Object],
W20210212-20:02:45.630(9)? (STDERR)       signedCookies: [Object: null prototype] {},
W20210212-20:02:45.631(9)? (STDERR)       query: {},
W20210212-20:02:45.631(9)? (STDERR)       Cookies: [__cookies],
W20210212-20:02:45.632(9)? (STDERR)       [Symbol(kCapture)]: false
W20210212-20:02:45.632(9)? (STDERR)     },
W20210212-20:02:45.633(9)? (STDERR)     outgoing: null,
W20210212-20:02:45.633(9)? (STDERR)     maxHeaderPairs: 2000,
W20210212-20:02:45.634(9)? (STDERR)     _consumed: true,
W20210212-20:02:45.635(9)? (STDERR)     onIncoming: [Function: bound parserOnIncoming],
W20210212-20:02:45.635(9)? (STDERR)     [Symbol(resource_symbol)]: HTTPServerAsyncResource {
W20210212-20:02:45.636(9)? (STDERR)       type: 'HTTPINCOMINGMESSAGE',
W20210212-20:02:45.636(9)? (STDERR)       socket: [Circular]
W20210212-20:02:45.637(9)? (STDERR)     }
W20210212-20:02:45.638(9)? (STDERR)   },
W20210212-20:02:45.638(9)? (STDERR)   on: [Function: socketListenerWrap],
W20210212-20:02:45.639(9)? (STDERR)   addListener: [Function: socketListenerWrap],
W20210212-20:02:45.640(9)? (STDERR)   prependListener: [Function: socketListenerWrap],
W20210212-20:02:45.640(9)? (STDERR)   _paused: false,
W20210212-20:02:45.641(9)? (STDERR)   _httpMessage: ServerResponse {
W20210212-20:02:45.641(9)? (STDERR)     _events: [Object: null prototype] { finish: [Array] },
W20210212-20:02:45.642(9)? (STDERR)     _eventsCount: 1,
W20210212-20:02:45.642(9)? (STDERR)     _maxListeners: undefined,
W20210212-20:02:45.643(9)? (STDERR)     outputData: [],
W20210212-20:02:45.643(9)? (STDERR)     outputSize: 0,
W20210212-20:02:45.644(9)? (STDERR)     writable: true,
W20210212-20:02:45.644(9)? (STDERR)     _last: false,
W20210212-20:02:45.645(9)? (STDERR)     chunkedEncoding: false,
W20210212-20:02:45.646(9)? (STDERR)     shouldKeepAlive: true,
W20210212-20:02:45.646(9)? (STDERR)     _defaultKeepAlive: true,
W20210212-20:02:45.647(9)? (STDERR)     useChunkedEncodingByDefault: true,
W20210212-20:02:45.647(9)? (STDERR)     sendDate: true,
W20210212-20:02:45.648(9)? (STDERR)     _removedConnection: false,
W20210212-20:02:45.649(9)? (STDERR)     _removedContLen: false,
W20210212-20:02:45.649(9)? (STDERR)     _removedTE: false,
W20210212-20:02:45.650(9)? (STDERR)     _contentLength: null,
W20210212-20:02:45.650(9)? (STDERR)     _hasBody: true,
W20210212-20:02:45.651(9)? (STDERR)     _trailer: '',
W20210212-20:02:45.652(9)? (STDERR)     finished: false,
W20210212-20:02:45.652(9)? (STDERR)     _headerSent: false,
W20210212-20:02:45.653(9)? (STDERR)     socket: [Circular],
W20210212-20:02:45.653(9)? (STDERR)     connection: [Circular],
W20210212-20:02:45.654(9)? (STDERR)     _header: null,
W20210212-20:02:45.654(9)? (STDERR)     _keepAliveTimeout: 5000,
W20210212-20:02:45.655(9)? (STDERR)     _onPendingData: [Function: bound updateOutgoingData],
W20210212-20:02:45.656(9)? (STDERR)     _sent100: false,
W20210212-20:02:45.656(9)? (STDERR)     _expect_continue: false,
W20210212-20:02:45.657(9)? (STDERR)     flush: [Function: flush],
W20210212-20:02:45.657(9)? (STDERR)     write: [Function: write],
W20210212-20:02:45.658(9)? (STDERR)     end: [Function: end],
W20210212-20:02:45.658(9)? (STDERR)     on: [Function: on],
W20210212-20:02:45.660(9)? (STDERR)     writeHead: [Function: writeHead],
W20210212-20:02:45.661(9)? (STDERR)     [Symbol(kCapture)]: false,
W20210212-20:02:45.661(9)? (STDERR)     [Symbol(kNeedDrain)]: false,
W20210212-20:02:45.662(9)? (STDERR)     [Symbol(corked)]: 0,
W20210212-20:02:45.662(9)? (STDERR)     [Symbol(kOutHeaders)]: null
W20210212-20:02:45.663(9)? (STDERR)   },
W20210212-20:02:45.663(9)? (STDERR)   [Symbol(asyncId)]: 4609,
W20210212-20:02:45.664(9)? (STDERR)   [Symbol(kHandle)]: TCP {
W20210212-20:02:45.665(9)? (STDERR)     reading: true,
W20210212-20:02:45.665(9)? (STDERR)     onconnection: null,
W20210212-20:02:45.666(9)? (STDERR)     _consumed: true,
W20210212-20:02:45.666(9)? (STDERR)     [Symbol(owner_symbol)]: [Circular]
W20210212-20:02:45.667(9)? (STDERR)   },
W20210212-20:02:45.667(9)? (STDERR)   [Symbol(kSetNoDelay)]: false,
W20210212-20:02:45.668(9)? (STDERR)   [Symbol(lastWriteQueueSize)]: 0,
W20210212-20:02:45.668(9)? (STDERR)   [Symbol(timeout)]: Timeout {
W20210212-20:02:45.669(9)? (STDERR)     _idleTimeout: 20000,
W20210212-20:02:45.669(9)? (STDERR)     _idlePrev: null,
W20210212-20:02:45.670(9)? (STDERR)     _idleNext: null,
W20210212-20:02:45.670(9)? (STDERR)     _idleStart: 252196,
W20210212-20:02:45.671(9)? (STDERR)     _onTimeout: [Function: bound ],
W20210212-20:02:45.671(9)? (STDERR)     _timerArgs: undefined,
W20210212-20:02:45.672(9)? (STDERR)     _repeat: null,
W20210212-20:02:45.672(9)? (STDERR)     _destroyed: false,
W20210212-20:02:45.673(9)? (STDERR)     [Symbol(refed)]: false,
W20210212-20:02:45.674(9)? (STDERR)     [Symbol(kHasPrimitive)]: false,
W20210212-20:02:45.674(9)? (STDERR)     [Symbol(asyncId)]: 4616,
W20210212-20:02:45.675(9)? (STDERR)     [Symbol(triggerId)]: 4615
W20210212-20:02:45.675(9)? (STDERR)   },
W20210212-20:02:45.676(9)? (STDERR)   [Symbol(kBuffer)]: null,
W20210212-20:02:45.676(9)? (STDERR)   [Symbol(kBufferCb)]: null,
W20210212-20:02:45.677(9)? (STDERR)   [Symbol(kBufferGen)]: null,
W20210212-20:02:45.677(9)? (STDERR)   [Symbol(kCapture)]: false,
W20210212-20:02:45.678(9)? (STDERR)   [Symbol(kBytesRead)]: 0,
W20210212-20:02:45.678(9)? (STDERR)   [Symbol(kBytesWritten)]: 0
W20210212-20:02:45.679(9)? (STDERR) }
W20210212-20:02:45.680(9)? (STDERR) [object Object]
W20210212-20:02:45.681(9)? (STDERR)     at IncomingMessage.handleError (packages/ostrio:files/server.js:487:19)
W20210212-20:02:45.681(9)? (STDERR)     at IncomingMessage.emit (events.js:314:20)
W20210212-20:02:45.682(9)? (STDERR)     at IncomingMessage.EventEmitter.emit (domain.js:483:12)
W20210212-20:02:45.682(9)? (STDERR)     at Socket.socketOnTimeout (_http_server.js:510:50)
W20210212-20:02:45.683(9)? (STDERR)     at Socket.emit (events.js:314:20)
W20210212-20:02:45.683(9)? (STDERR)     at Socket.EventEmitter.emit (domain.js:483:12)
W20210212-20:02:45.684(9)? (STDERR)     at Socket._onTimeout (net.js:483:8)
W20210212-20:02:45.685(9)? (STDERR)     at listOnTimeout (internal/timers.js:554:17)
W20210212-20:02:45.685(9)? (STDERR)     at processTimers (internal/timers.js:497:7)
I20210212-20:02:49.848(9)? [FilesCollection] [Upload] [HTTP] Got #1/20 chunks, dst: 20210125_214710.jpg
I20210212-20:02:50.964(9)? [FilesCollection] [Upload] [HTTP] Got #1/20 chunks, dst: 20210125_214710.jpg
I20210212-20:03:21.092(9)? [FilesCollection] [Upload] [HTTP] Got #2/20 chunks, dst: 20210125_214710.jpg
I20210212-20:03:21.808(9)? [FilesCollection] [Upload] [HTTP] Got #2/20 chunks, dst: 20210125_214710.jpg

```
  
![image](https://user-images.githubusercontent.com/44692596/107760792-af02ef00-6d6d-11eb-84c9-b9ba1c240213.png)

I'm using almost the exact same code as used in the examples (just different variable names), but it's painfully slow.

The VM that's hosting it is on my local PC, and uploading anything takes minutes.

Doing it on the VM itself works fast.

**Comment by dr-dimitru** [comment] 2021-02-12 16:45
@michael-trinity it's clear from the logs — `Socket.socketOnTimeout` for the some reason your socket is timed out.
I believe you uploading file somewhere under the meteor's project directory, when meteor build system detect new file it starts rebuilding itself (*you have this in the posted logs above as well*) `Client modified -- refreshing`.

Please, pay attention to our [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq) section. 

> To keep your storage persistent during development use an absolute path outside of your project folder, e.g. `/data` directory.

Where's leading slash of `/data` points to the root of the file system

**Comment by dr-dimitru** [comment] 2021-02-12 16:52
@michael-trinity just saw `assets/app/uploads/Images` as `storagePath` at the beginning of the log.

Anyways try first setting `storagePath` to the directory outside of Meteor project. Then if this won't help — set `transport` to `ddp`. Then if this won't help neither — come back here with your collection definition and upload/insert code.

Anyways keep this thread updated

**Comment by michael-trinity** [comment] 2021-02-12 22:32
> @michael-trinity just saw `assets/app/uploads/Images` as `storagePath` at the beginning of the log.
> 
> Anyways try first setting `storagePath` to the directory outside of Meteor project. Then if this won't help — set `transport` to `ddp`. Then if this won't help neither — come back here with your collection definition and upload/insert code.
> 
> Anyways keep this thread updated

I changed the directory to `/uploads` and made sure meteor has writing rights to it.
When it starts uploading, the file gets created but stays at 0b for a very long time, as if no data gets sent.

I'm using the `demo-simplest-upload` with the file `images.collection.js` edited with `storagePath: () => '/uploads',` added.

```
I20210213-07:28:03.410(9)? [FilesCollection.storagePath] Set to: /uploads
=> Started your app.

=> App running at: http://192.168.1.206:3000
I20210213-07:28:11.449(9)? [FilesCollection] [find({}, undefined)]
I20210213-07:28:18.959(9)? [FilesCollection] [File Start Method] 20210125_214710.jpg - 4kCruWXbxYfJuBzQe
I20210213-07:28:18.960(9)? [FilesCollection] [Upload] [DDP Start Method] Got #-1/10 chunks, dst: 20210125_214710.jpg
```

this is how it stays for minutes without progressing.

Here's the JS for that file:
```
import { Meteor }          from 'meteor/meteor';
import { FilesCollection } from 'meteor/ostrio:files';

const Images = new FilesCollection({
  debug: true,
  collectionName: 'Images',
  allowClientCode: false, // Disallow remove files from Client
  storagePath: () => '/uploads',
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 1024 * 1024 * 10 && /png|jpe?g/i.test(file.extension)) {
      return true;
    }
    return 'Please upload image, with size equal or less than 10MB';
  }
});

if (Meteor.isServer) {
  Images.denyClient();
  Meteor.publish('files.images.all', function () {
    return Images.find().cursor;
  });
} else {
  Meteor.subscribe('files.images.all');
}

export default Images;
```

**Comment by dr-dimitru** [comment] 2021-02-12 22:43
@michael-trinity 

1. Any clients errors?
2. Can you measure speed of your storage? With `hdparm -Tt /dev/sda`

**Comment by michael-trinity** [comment] 2021-02-12 22:58
@dr-dimitru 
1. No errors at all, just very slow requests in the network tab. Although after a while I start seeing this.
![image](https://user-images.githubusercontent.com/44692596/107831215-e2c33080-6dd0-11eb-96cd-5fd387f90b9e.png)

![image](https://user-images.githubusercontent.com/44692596/107831328-2c138000-6dd1-11eb-847b-a0b2847f60d0.png)


2. Sure, it's running on an SSD
```
 Timing cached reads:   50644 MB in  1.89 seconds = 26816.84 MB/sec
SG_IO: bad/missing sense data, sb[]:  70 00 05 00 00 00 00 0a 00 00 00 00 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 Timing buffered disk reads: 2442 MB in  3.00 seconds = 812.92 MB/sec
```

It really feels like the server is rejecting any uploads from other IP's, although the firewall is completely off.

**Comment by dr-dimitru** [comment] 2021-02-12 23:13
> It really feels like the server is rejecting any uploads from other IP's, although the firewall is completely off.

@michael-trinity those `.pause()` and `.continue()` logs are not okay. It means Client gets disconnected from server.
This is related to `Socket.socketOnTimeout` from your first post. I think Server restarts, gets disconnected, or stopes receiving connections. Is there any reason why it might not want to open more than one/two connections per client?

I can recommend to try to launch meteor with `--production` flag or even better try __build__ version

**Comment by michael-trinity** [comment] 2021-02-12 23:37
@dr-dimitru 
to be honest I have no idea why it's not accepting connections, doing anything else besides uploading is fine.
Database reactivity is perfect and fast. 

Using --production or building the app doesn't have an effect either.

**Comment by dr-dimitru** [comment] 2021-02-13 06:20
@michael-trinity have you tried other browsers? You haven't mentioned which one you're using

**Comment by michael-trinity** [comment] 2021-02-13 07:14
> @michael-trinity have you tried other browsers? You haven't mentioned which one you're using

yes all of them besides safari, edge, internet explorer, chrome and firefox.

tried direct meteor hosting on the vm (just running dev), tried production and with nginx proxy. All result in not being able to upload files usually or very very slow.

**Comment by dr-dimitru** [comment] 2021-02-13 17:11
@michael-trinity you're the first to file such report.

Could you test it with this demo app -- https://github.com/veliovgroup/meteor-files-website

**Comment by michael-trinity** [comment] 2021-02-14 05:00
@dr-dimitru Same issue, I think it might just be the VM that's somehow screwed.
I'll try setting up a new VM and see if a different OS version works instead.

thanks for the help! If Ubuntu 18.04 works I'll post here

**Comment by dr-dimitru** [comment] 2021-02-17 18:27
@michael-trinity let me know if it's fixed or if you require further help

**Comment by michael-trinity** [comment] 2021-02-18 13:19
@dr-dimitru I couldn't get it to work with Ubuntu, in the end I opted to just use a MUP deploy to Docker test and that worked. Not sure what the issue was as the Ubuntu install was completely fresh.

**Comment by dr-dimitru** [comment] 2021-02-18 16:45
@michael-trinity I'm glad you are able to run it. Regarding Ubuntu setup — it's very individual as there are a lot of ways to implement it. Keep this thread updated if you will find its cause. Feel free to close it in case if the issue is solved on your end, at least for now

**Comment by dr-dimitru** [comment] 2021-03-15 09:14
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Closed by dr-dimitru** 2021-03-15 09:14 UTC
Labels: question
