### ISSUE TITLE
Adding version to an existing file record from the client

### ISSUE THREAD

**Issue by schlaegerz** [veliovgroup/Meteor-Files#777] opened 2020-11-18 23:10 UTC
Is there a way to upload a new version to an existing file record? I only see information to insert which then allows the server to add multiple versions, but I would like to add a version to the existing item from the client

For instance if I had a user that uploaded an image, but he wanted to upload the same image but in a different language, I would like it to be all contained in a single collection item and then deciding on the server which one to show, rather than adding a whole new collection item.

**Comment by dr-dimitru** [comment] 2020-11-18 23:43
Hello @schlaegerz,

At this moment library has no such functionality.
Current implementation targeted different usage. The best example would be — upload an image and generate its multiple versions of different sizes on a Server.

Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment] 2021-02-04 21:45
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Closed by dr-dimitru** 2021-02-04 21:45 UTC
Labels: question
