### ISSUE TITLE
it doesn't not work on android platfrom

### ISSUE THREAD

**Issue by anglepan** [VeliovGroup/Meteor-Files#444] opened 2017-06-09 09:54 UTC
### I'm having an issue:
 1. it works well on web and ios
 2. but not work on  android (cordova app)
  
### my server:
 1. meteor 1.5
 2. ostrio:cookies@2.2.1
 3. ostrio:files@1.7.17

**Comment by dr-dimitru** [comment] 2017-06-09 13:21
Hello @anglepan ,

Thank you for report.
 1. Could you describe what actually is not working and how we can reproduce it.
 2. Is there any Client or Server errors?
 3. Enable debug mode and attach its logs from both Server and Client
 4. Make sure your issue is not related to #159

**Comment by dr-dimitru** [comment] 2017-06-18 10:39
Hello @anglepan ,

This should be fixed in [`v1.8.0`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.8.0) please update to the latest release and let me know if it solves this issue.

**Comment by dr-dimitru** [comment] 2017-07-18 03:29
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Closed by dr-dimitru** 2017-07-18 03:29 UTC
Labels: question

**Comment by csKangGdcomm** [comment] 2018-05-24 07:04
I got these error.

on web and ios simulator works fine but

on android simulator, I cann't show image.

The page has the valid url ( I checked the string through normal text ).

first of all I checked css, 

before removing css, it shows nothing ( like display:non )

after removing css, it shows only default broken image  with alt message.....

there is no special error message on server side, 

I cann't check the client side error ( I think android simurator show both error message )

Can you give me some advice? Thank you!

**Comment by dr-dimitru** [comment] 2018-05-24 07:27
Hello @csKangGdcomm ,
Have you set [`ROOT_URL` env.var](https://docs.meteor.com/environment-variables.html#ROOT-URL)?

**Comment by csKangGdcomm** [comment] 2018-05-24 07:36
I tried 
`ROOT_URL=http://10.0.1.101:3000 meteor run android --settings settings.json --verbose`

So url is changed like below

`http://10.0.1.101:3000/cdn/storage/ImageFiles/qhfERa9GMFyL8CWm8/original/qhfERa9GMFyL8CWm8.jpeg`

But still image is not showing

**Comment by dr-dimitru** [comment] 2018-05-24 07:40
@csKangGdcomm could you access this picture via browser? Directly via URL:
```
http://10.0.1.101:3000/cdn/storage/ImageFiles/qhfERa9GMFyL8CWm8/original/qhfERa9GMFyL8CWm8.jpeg
```

**Comment by dr-dimitru** [comment] 2018-05-24 07:41
@csKangGdcomm could you confirm what the file exists? Could you observe it through Terminal/Finder/Explorer?

**Comment by csKangGdcomm** [comment] 2018-05-24 08:00
I find the way to see the image, your advice help me a lot,

I am using mac So, `10.0.2.2` is the special address for access local mac machine.

So I started android simulator like below

`ROOT_URL=http://10.0.2.2:3000 meteor run android --settings settings.json --verbose`

And then I can see the images!

Thank you a lot!!!
