### ISSUE TITLE
IE 11 Support

### ISSUE THREAD

**Issue by mozibrand** [VeliovGroup/Meteor-Files#445] opened 2017-06-10 04:00 UTC
I have no problem with IE, I have no problem with the Google browser, but IE error, all pages are not open, the error code is as follows:

![12](https://user-images.githubusercontent.com/24447931/26999772-567e944a-4dd4-11e7-857b-e7c39002bfde.jpg)

How to solve it

this is my website: http://sztopfar.mozibrand.com  IE not open

**Comment by dr-dimitru** [comment] 2017-06-10 04:07
Hello @mozibrand ,

 1. What the errors says?
 2. Could you make a same screen shot but with debug enabled? (See `debug` flag in a [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor))
 3. Does server has any errors?
 4. What is IE and Windows version?

**Comment by mozibrand** [comment] 2017-06-10 04:28
1: error see screenshot


![1](https://user-images.githubusercontent.com/24447931/26999892-b4287604-4dd6-11e7-8e71-420bc86ce24f.jpg)

![3](https://user-images.githubusercontent.com/24447931/26999923-6371714c-4dd7-11e7-8dcd-a551e7b3d715.jpg)


![3](https://user-images.githubusercontent.com/24447931/26999914-44ca973c-4dd7-11e7-889e-21dfbae2c06f.jpg)

In IE, it's not open

3: In the Google browser, after uploading the image, it doesn't show up

![4](https://user-images.githubusercontent.com/24447931/26999961-30238c7a-4dd8-11e7-989b-5dc66782b155.jpg)

4: windows version is windows 10, IE version is IE 11

**Comment by mozibrand** [comment] 2017-06-10 04:30
I'm trying to set up a git project, do you have time to help me see what the problem is because I don't speak English well enough to speak clearly

**Comment by dr-dimitru** [comment] 2017-06-10 04:31
> I'm trying to set up a git project, do you have time to help me see what the problem is because I don't speak English well enough to speak clearly

Okay, but first problem we have - I have no access to Windows. So, I'm not able to reproduce it.

**Comment by dr-dimitru** [comment] 2017-06-10 04:34
1. Make sure `es5-shim` and `ecmascript` packages is installed
 2. Make sure you're on the latest release of Meteor and Meteor-Files (`ostrio:files`)

**Comment by mozibrand** [comment] 2017-06-10 04:34
Thank you for replying to me now, I guess you should be in the middle of the night in China

There's no relationship. You can use IE to try and see if the MAC can install 360 tests

http://www.360.cn/mac/

**Comment by mozibrand** [comment] 2017-06-10 04:37
my meteor version is 1.5, npm is 4.6.1, ostrio:files version is  latest release, packages list is: 
# 这是 Inspinia admin 默认配置的包
less@2.7.9                  # less 样式包
fortawesome:fontawesome     # 字体图标
jquery@1.11.10              # jQuery
dbarrett:dropzonejs         # DropzoneJS是一个开源库，可以通过图像预览提供拖放文件上传
twbs:bootstrap@3.3.6        # Bootstrap
meteor-base@1.1.0           # Meteor 基础包
mobile-experience@1.0.4     # Meteor 默认移动端体验
mongo@1.1.18                # Meteor 默认 MongoDB包
blaze-html-templates@1.0.4  # Blaze 模板包
session@1.1.7               # Session 包
tracker@1.1.3               # Meteor's client-side reactive programming library
logging@1.1.17              # 日志管理
reload@1.1.11               #
random@1.0.10               #
ejson@1.0.13
spacebars@1.0.12
check@1.2.5
standard-minifier-css@1.3.4 # CSS minifier run for production mode
standard-minifier-js@2.1.0  # JS minifier run for production mode
shell-server@0.2.3          # Server-side component of the `meteor shell` command
autoupdate@1.3.12
kadira:blaze-layout         # 渲染Blaze模板
kadira:flow-router          # Flow-router
zimme:active-route          #

# 另外添加的功能包
accounts-ui@1.1.9           # Meteor 默认用户系统UI包
accounts-password@1.3.6     # Meteor 默认用户系统
useraccounts:bootstrap      # Meteor 默认用户系统样式
useraccounts:flow-routing   # Meteor 默认用户系统路由

juliancwirko:s-alert        # 美化弹出alert
juliancwirko:s-alert-slide  # 右侧弹出
juliancwirko:s-alert-scale  # 美化弹出alert 动画效果

meteor-platform             # 表单检测
underscore@1.0.10           # Meteor 核心JS库
#momentjs:moment            # 时间包：显示为多久前
rzymek:moment-locale-zh-cn  # 时间包中文化

ostrio:files               # ostrio:files 文件上传

#cfs:standard-packages       # 换 Meteor-CollectionFS
#cfs:gridfs
#cfs:filesystem
#iyyang:cfs-aliyun

dschulz:jquery-qrcode       # 生成二维码插件（液态码）
reactive-var@1.0.11         # 页面全局变量

themeteorchef:jquery-validation  # 表单验证
nolimits4web:swiper         # 轮播滑动插件
dynamic-import
udondan:slick

**Comment by mozibrand** [comment] 2017-06-10 04:40
Just a moment, please. I'll install it es5-shim and ecmascript

**Comment by dr-dimitru** [comment] 2017-06-10 10:30
@mozibrand is this one solved?

**Comment by mozibrand** [comment] 2017-06-11 02:37
no no no, I created a project, is new, you just installed the package, not run directly, an error, do nothing, only your package installed, in IE an error

**Comment by mozibrand** [comment] 2017-06-11 02:45
![11](https://user-images.githubusercontent.com/24447931/27007791-2684644a-4e92-11e7-9290-fb60f48dae13.jpg)

============
meteor create ostriofiles
cd ostriofiles
meteor add ostrio:files
meteor 
=============
![1211](https://user-images.githubusercontent.com/24447931/27007830-1a785cfa-4e93-11e7-9517-561e96339d7f.jpg)

**Comment by mozibrand** [comment] 2017-06-11 02:50
@dr-dimitru Just installed one package, a new meteor project, really doesn't support IE?

**Comment by dr-dimitru** [comment] 2017-06-11 12:10
1. What the errors says?
 2. Could you make a same screen shots but with debug enabled? (See `debug` flag in a [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor))

**Comment by mozibrand** [comment] 2017-06-11 12:56
![121212](https://user-images.githubusercontent.com/24447931/27011136-32e857fe-4ee8-11e7-95a4-54ff3ffebf3c.jpg)

1: I tried Meteor - CollectionFS, in IE is ok, but bad to use, pictures showed not, i want to use ostrio: files, but ostrio: files for ie not open. create a new meteor project, only installed ostrio: files package, Also have the wrong

**Comment by mozibrand** [comment] 2017-06-11 17:30
How do you solve this problem，thank you very mach， In a hurry with

**Comment by mozibrand** [comment] 2017-06-11 17:31
I use the translation software, sometimes the tone is wrong or not friendly, please excuse me, because my English is very rubbish

**Comment by mozibrand** [comment] 2017-06-11 17:33
I'm in a hurry. You have a very good bag. I don't want to use it any more Meteor - CollectionFS，He had no one to maintain, it was a discarded bag

**Comment by mozibrand** [comment] 2017-06-11 17:33
@dr-dimitru #

**Comment by dr-dimitru** [comment] 2017-06-11 17:45
What the errors says? On the screenshot at the IE console, where is `something meteorInstall` and above it.

**Comment by mozibrand** [comment] 2017-06-11 18:01
SCRIPT1002: 语法错误
ostrio_files.js (4138,51)

SCRIPT5007: 无法获取未定义或 null 引用的属性 “FilesCollection”
global-imports.js (7,1)

SCRIPT5009: "meteorInstall" 未定义
app.js(1,1)

====================================

SCRIPT1002: grammatical errors
Ostrio_files.js (4138,51)
SCRIPT5007: unable to retrieve an attribute "FilesCollection" of undefined or null references
Global imports.js (7, 1)
SCRIPT5009: "meteorInstall" is undefined
App. Js (1, 1)

**Comment by mozibrand** [comment] 2017-06-11 18:05
Does that make sense? Can you solve it? This is the addition of the package. I didn't write a single line of code. In IE11, no, it's not possible to not support IE11

**Comment by mozibrand** [comment] 2017-06-11 18:07
meteor create demo
cd demo
meteor add ostrio:files
meteor update
meteor

in ie11, error

**Comment by mozibrand** [comment] 2017-06-11 18:15
:)

**Comment by dr-dimitru** [comment] 2017-06-11 19:06
Now it's more clear.
Looks like `import` statement is missing:
```js
import { FilesCollection } from 'meteor/ostrio:files';
```

Or use globally defined (__note:__ will be deprecated in future):
```js
Meteor.Files
```

**Comment by dr-dimitru** [comment] 2017-06-11 19:14
> I didn't write a single line of code.

Hmm.. this is weird. Try to check if error will gone with `--production` flag:
```shell
meteor --production
```

**Comment by laosb** [comment] 2017-06-12 02:04
@mozibrand @dr-dimitru 

@dr-dimitru He has explained his problem in Meteor China Community, and I have investigated it with him. I would say sorry representing him for his poor English and thank you for your warm help and hardwork on this package!

`ostrio:files` depends the npm module `fs-extra`, which is loaded on the client-side(is this an intended behavior?). That package is in ES6 and has no transpilation conducted by itself. While meteor doesn't transpile NPM modules, this problem happened due to the fact that IE11 doesn't support Arrow Functions. The first error in @mozibrand 's screenshot is just caused by https://github.com/jprichardson/node-fs-extra/blob/master/lib/util/assign.js#L7-L11 .

So, do you have any suggestions on how to solve this problem? Would you like me posting another issue respecting the real problem to track, or just say you don't want to support legacy browsers like IE11?

Thank you for your hardwork!

**Comment by mozibrand** [comment] 2017-06-12 02:31
@laosb Thank you very much!

**Comment by mozibrand** [comment] 2017-06-12 03:56
@dr-dimitru I look forward to your response, thanks

**Comment by dr-dimitru** [comment] 2017-06-12 14:02
Hello @mozibrand @laosb ,

> npm module fs-extra, which is loaded on the client-side(is this an intended behavior?)

No, this shouldn't happen. `fs-extra` is meant to be used on Server only.

> So, do you have any suggestions on how to solve this problem?

Now, only falling back to older release.

> or just say you don't want to support legacy browsers like IE11?

I would support IE 11, and make sure backend NPM packages only loaded on Server.

The big update is coming. We're moving from CoffeeScript to ES6 and this should solve all current issues. But I can't tell you when it will be published.

I'll mark this as a bug. Thank you for report.
Let me know if downgrading to older release temporarily fixes this issue.

**Comment by haojia321** [comment] 2017-06-17 18:27
Having same issue with Windows 10 IE 11. Edge is working fine.

**Comment by dr-dimitru** [comment] 2017-06-18 10:38
Hello @mozibrand @haojia321 @laosb 

This should be fixed in [`v1.8.0`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.8.0) please update to the latest release and let me know if it solves this issue.

**Comment by laosb** [comment] 2017-06-18 10:54
@mozibrand is now trying it out - let's see if it works!

**Comment by mozibrand** [comment] 2017-06-18 10:57
Thank you very much, and now we've been able to support IE9, and congratulations on getting a lot of fans back from CFS back to the ostrio: files

**Closed** 2017-06-18 10:59 UTC
Labels: bug

**Comment by dr-dimitru** [comment] 2017-06-18 11:05
@laosb thank you for stepping in.
@mozibrand thank you for contribution. Do you have a chance to test other IEs? 8, 10, 11, Edge?
I'm doing this blindly as have limited access to Win 7 with IE 8 onboard, which wont even display something. It will be great to know where it work or not. Thank you

**Comment by dr-dimitru** [comment] 2017-06-18 11:08
Mentioned you in [release](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.8.0), thanks a lot once again!

**Comment by laosb** [comment] 2017-06-18 11:12
@dr-dimitru Great, keep it up!

**Comment by mozibrand** [comment] 2017-06-21 08:31
@dr-dimitru Ie7,ie8 is not supported, ie9, ie11 is supported,  , ie7 , ie8 is still like my screenshot

**Comment by mozibrand** [comment] 2017-06-21 08:34
edge is supported , very good

**Comment by mozibrand** [comment] 2017-06-21 09:48
The meteor itself does not support IE7.8, so it is unsolvable，It's great to be able to support IE9 now，Thanks again

**Comment by dr-dimitru** [comment] 2017-06-21 13:36
This week I've been working with bizarre browsers including Maxthon, UCBrowser and IE.
Made it work in IE>=9, latest Maxthon and some version of UCBrowser which is recognized as Chrome 37.
Do you have any experience with Meteor on Maxthon and/or UCBrowser? As far as I know Maxthon is widely used in China.

**Comment by laosb** [comment] 2017-06-21 14:31
Maxthon is no longer popular in China at this moment. Sounds like you have covered a big part of China specific browsers since you can simply see them as older versions of Chrome. Amazing!

**Comment by laosb** [comment] 2017-06-21 14:36
If you want to know the marketshare in China, you can refer to [this analysis conducted by Baidu](, with all data they get with their GoolgeAnalytics-liked producted.

**Comment by dr-dimitru** [comment] 2017-06-21 14:51
> Maxthon is no longer popular in China at this moment

That's great, less browsers - less hassle :)
Thank you a lot for this info.

**Comment by runlevelsix** [comment] 2017-08-16 21:11
Hi,
I've recently had this error in IE11, using `ostrio:files@1.8.2`.

There are over 100 errors in the console that start with a purported syntax error in `modules.js` on Line 14584, Column 51. This is an arrow function, which I realize IE11 does not support. However, it is from the `fs-extra` package, which should never be loaded client side.

I understood from the comments above that this issue should have been fixed in version 1.8.0. Is this a regression?

**Comment by runlevelsix** [comment] 2017-08-16 22:24
Ah! I've fixed the issue!

My code was using `fs = require('fs-extra');`.

When I updated it to be `fs = Npm.require('fs-extra');`, all of my IE11 problems went away. I've certainly learned a lesson ;-)

**Comment by dr-dimitru** [comment] 2017-08-16 22:49
@runlevelsix you should not import `fs` and/or `fs-extra` on the *Client*

**Comment by runlevelsix** [comment] 2017-08-17 18:19
I agree, my code is in a `/lib` folder, but is also in side a `Meteor.isServer` block. 

The only solution which worked was using `var fs = Npm.require('fs-extra');` rather than simply `var fs = require('fs-extra');`. 

I think that because Meteor (Babel?) was doing all of the code splitting, it got confused by the `require` and put `fs-extra` into the client-side code bundle, regardless of my code only using it server side.

**Comment by dr-dimitru** [comment] 2017-08-17 18:36
Yes, it's caused by Meteor's compilation process. If is sees `require` or `import` keywords it will preload mentioned libraries with no respect to `Meteor.isServer` block.

That's why we have been forced to implement [exact code splitting](https://github.com/VeliovGroup/Meteor-Files/commit/e26ca7c35a84eeead207e0612eac9c6ebe730c61).
