### ISSUE TITLE
Confusing typo in wiki

### ISSUE THREAD

**Issue by janjackson** [VeliovGroup/Meteor-Files#620] opened 2018-06-14 13:38 UTC
https://github.com/VeliovGroup/Meteor-Files/wiki/remove

is about how to remove Images.

Images.link() needs to be replaced with Images.remove()

I could not find the file in the repo, so sry that it's an issue and not a PR

Thanks a lot for the great work! :)

**Comment by dr-dimitru** [comment] 2018-06-14 17:45
@janjackson good catch ；）
Fixed. 
FYI: Up-to-date docs always can be found at [`docs` directory](https://github.com/VeliovGroup/Meteor-Files/tree/master/docs)

Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment] 2018-06-15 07:31
Feel free to reopen it in case if the issue is still persists on your end.

**Closed by dr-dimitru** 2018-06-15 07:31 UTC
Labels: Documentation, question
