### ISSUE TITLE
Stream error makes server restart

### ISSUE THREAD

**Issue by PolGuixe** [VeliovGroup/Meteor-Files#370] opened 2017-03-02 01:04 UTC
When the error below is thrown, the server is restarted. Is it normal?

```
W20170226-01:07:58.347(-5)? (STDERR) stream.js:74
W20170226-01:07:58.355(-5)? (STDERR)       throw er; // Unhandled stream error in pipe.
W20170226-01:07:58.355(-5)? (STDERR)       ^
W20170226-01:07:58.355(-5)? (STDERR)
W20170226-01:07:58.355(-5)? (STDERR) Error: getaddrinfo ENOTFOUND images-local.la-jungla.es images-local.la-jungla.es:443
W20170226-01:07:58.355(-5)? (STDERR)     at errnoException (dns.js:27:10)
W20170226-01:07:58.356(-5)? (STDERR)     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
```

**Comment by dr-dimitru** [comment] 2017-03-02 10:30
Hi @PolGuixe ,

No, definitely not ok. What method is used? `.insert()`, `.write()` or `.load()`?
Error comes from Node.js, as stream.js is its internal module

**Comment by PolGuixe** [comment] 2017-03-02 17:51
**Context:** 
- Using knox to upload to S3
- Using cloudfront for donwload. 

**Way to reproduce it:**
- Disable cloudfront or your DNS routing. 

**Error:**
```
W20170302-12:48:09.559(-5)? (STDERR) stream.js:74
W20170302-12:48:09.582(-5)? (STDERR)       throw er; // Unhandled stream error in pipe.
W20170302-12:48:09.583(-5)? (STDERR)       ^
W20170302-12:48:09.583(-5)? (STDERR)
W20170302-12:48:09.595(-5)? (STDERR) Error: getaddrinfo ENOTFOUND images-local.la-jungla.es images-local.la-jungla.es:443
W20170302-12:48:09.595(-5)? (STDERR)     at errnoException (dns.js:27:10)
W20170302-12:48:09.603(-5)? (STDERR)     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
=> Exited with code: 1
I20170302-12:48:32.788(-5)? Kadira: completed instrumenting the app
=> Meteor server restarted
```

**Comment by dr-dimitru** [comment] 2017-03-02 18:45
So, it's AWS issues while using Knox as a driver, right?

`ENOTFOUND` looks like URL address wasn't found, isn't it?

**Comment by PolGuixe** [comment] 2017-03-02 18:46
I am disabling Cloudfront on purpose. To reproduce the error.

**Comment by dr-dimitru** [comment] 2017-03-02 18:50
But Cloudfront is required option for Knox driver

**Comment by PolGuixe** [comment] 2017-03-02 19:01
Yes I know, I it is enabled always. 

When S3 failed recently, I realized that an error made the whole server to restart. This was worrying.

**Comment by dr-dimitru** [comment] 2017-03-02 19:07
#307 is still pending. `knox` is outdated, and it might be caused by this fact.
I'm looking forward to Evaporate, but have no right moment to put my hands on.
I'm pretty sure it isn't a big deal to switch Knox to Evaporate.

**Comment by PolGuixe** [comment] 2017-03-02 20:33
@dr-dimitru I had a quick look at evaporate but it seems a client side uploader to S3. I need to look in more detail

**Comment by dr-dimitru** [comment] 2017-03-03 09:41
Hi @PolGuixe you're right.
I'm assuming it's better to stick with official [AWS SDK](https://aws.amazon.com/sdk-for-node-js/)
Docs reference - http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html

**Comment by PolGuixe** [comment] 2017-03-03 15:15
@dr-dimitru It makes sense. 

It is a question that may be can be asked to the wider community. Should we open a another issue to discuss this matter?

**Comment by dr-dimitru** [comment] 2017-03-03 15:18
Hi @PolGuixe ,

I believe #307 is in general targeted to update demo app and wiki with new lib for S3, so it fits

**Comment by dr-dimitru** [comment] 2017-03-03 15:19
You can close this one in favor of #307

**Closed** 2017-03-03 15:20 UTC
Labels: AWS S3
