### ISSUE TITLE
ostrio_files.js error when using opera

### ISSUE THREAD

**Issue by sebastianlutter** [VeliovGroup/Meteor-Files#293] opened 2016-11-18 20:47 UTC
When I try to test an application on Opera 12.16 Build 1860 (Debian 8, x86_64 system) I get an client error in ostrio_files.js line 1647:
```
Unhandled Error: Cannot convert '_URL' to object
											this._webWorkerUrl = _URL.createObjectURL(new Blob(['"use strict";self.onmessage=function(a){if(a.data.ib===!0)postMessage({bin:a.data.f.slice(a.data.cs*(a.data.cc-1),a.data.cs*a.data.cc),chunkId:a.data.cc});else{var b;self.FileReader?(b=new FileReader,b.onloadend=function(c){postMessage({bin:(b.result||c.srcElement||c.target).split(",")[1],chunkId:a.data.cc,s:a.data.s})},b.onerror=function(a){throw(a.target||a.srcElement).error},b.readAsDataURL(a.data.f.slice(a.data.cs*(a.data.cc-1),a.data.cs*a.data.cc))):self.FileReaderSync?(b=new FileReaderSync,postMessage({bin:b.readAsDataURL(a.data.f.slice(a.data.cs*(a.data.cc-1),a.data.cs*a.data.cc)).split(",")[1],chunkId:a.data.cc})):postMessage({bin:null,chunkId:a.data.cc,error:"File API is not supported in WebWorker!"})}};'], {
												type: 'application/javascript'//
											})); //
										})
```

The command in the next line (1646) sets _URL to undefined, which obviously causes the error on line 1647:
```
_URL = window.URL || window.webkitURL || window.mozURL; //
```

**Versions:**
Meteor 1.4.2.3
ostrio:files@1.7.5

This only happens in Opera, the application runs well on Firefox, Chrome.

**Comment by dr-dimitru** [comment] 2016-12-12 14:14
Hello @sebastianlutter 

Thank you for report, sorry for delay.

 1. Is this Mac, Linux or Win?
 2. Which Opera version?

**Comment by dr-dimitru** [comment] 2016-12-12 14:33
Tested on Mac Opera (43.0.2431.0) and (41.0.2353.69), can't reproduce

**Comment by sebastianlutter** [comment] 2016-12-14 14:31
1. Is this Mac, Linux or Win?  **Debian 8, x86_64 system**
 2. Which Opera version?
```
user@work:~$ sudo apt-cache show opera
Package: opera
Version: 12.16.1860
Architecture: amd64
[ . . . ]
Homepage: http://www.opera.com/browser/
Priority: optional
Section: non-free/web
Filename: pool/non-free/o/opera/opera_12.16.1860_amd64.deb
[ ... ]
```

**Comment by dr-dimitru** [comment] 2016-12-14 14:36
This will be fixed in next release

**Comment by sebastianlutter** [comment] 2016-12-14 15:07
This is the result of _URL when I ran in operas console:
```
>>> _URL = window.URL || window.webkitURL || window.mozURL || window.msURL || window.oURL || false;
false
```

Then the condition the line after would be false
```
if window?.Worker and window?.Blob and _URL
```

I have no understanding of the surrounding code, is this what you expected?

**Comment by dr-dimitru** [comment] 2016-12-14 15:27
Yes, 

Basically, BlobBuilder is not supported, so it will fall-back to request Worker code over the wire.

**Closed** 2016-12-15 15:55 UTC
Labels: bug, Opera

**Comment by dr-dimitru** [comment] 2016-12-15 16:00
Hi @sebastianlutter 

Published as [v1.7.6](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.6)
Could you please update, and confirm as fixed on your end?

**Comment by sebastianlutter** [comment] 2016-12-19 21:05
updated to v1.7.6, confirm it is working now (Opera 12.16.1860 on Debian 8)

Thanks :)

**Comment by dr-dimitru** [comment] 2016-12-19 21:10
@sebastianlutter great, thank you for report.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
