### ISSUE TITLE
Update @1.14.2 to @1.14.3 Package missing Meteor-Files library source and so on.

### ISSUE THREAD

**Issue by kakadais** [veliovgroup/Meteor-Files#772] opened 2020-11-09 09:33 UTC
After update the package from 1.14.2 to 1.14.3,
I encounted crash with error for missing package
meteor package mrt:filesize
npm package fs-extra
so I added it manually.

This is okay because I understand that this package wans to allow the free control 3rd party packages by developer,
and this is just a example.

But next,
- /import/lib/core.js and web-push.js import error in Meteor-Files library,
so I copy & add the files from Meteor-Files project manually and install npm webpush package as well.
- webPush package import error on client side
the package looks like server side only, so I just commented it all temporary
- error for undefined access for 'native'
![image](https://user-images.githubusercontent.com/5265343/98523731-97712180-22b9-11eb-882f-36964a77dab3.png)

The story is my journey for now, 
and I think I need to check 'Did I misunderstand something' stuff.

I updated these to working project,
- Meteor Pacakge
![image](https://user-images.githubusercontent.com/5265343/98523983-f040ba00-22b9-11eb-8a94-d02aff30f2c1.png)
![image](https://user-images.githubusercontent.com/5265343/98524000-f898f500-22b9-11eb-94e5-2e8abdd09d87.png)
- Npm Package
![image](https://user-images.githubusercontent.com/5265343/98524036-051d4d80-22ba-11eb-87fb-b3c4c2c72367.png)
- import Meteor-Files Lib
![image](https://user-images.githubusercontent.com/5265343/98524078-14040000-22ba-11eb-9181-a39fdc8172ca.png)

**Comment by kakadais** [comment] 2020-11-09 09:36
Last error seems like fs-extra issue,
and I just almost followed your example.

```
import { Meteor } from 'meteor/meteor';
import { Random } from 'meteor/random';
import { filesize } from 'meteor/mrt:filesize';
import { FilesCollection } from 'meteor/ostrio:files';
import { _app, Collections } from '/imports/lib/core.js';
// import { webPush } from '/imports/server/web-push.js';

import fs from 'fs-extra';
import S3 from 'aws-sdk/clients/s3';

// AWS:S3 usage:
// Read: https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration
// env.var example: S3='{"s3":{"key": "xxx", "secret": "xxx", "bucket": "xxx", "region": "xxx""}}'
let useS3 = false;
let client;

const bound = Meteor.bindEnvironment((callback) => {
  return callback();
});

if (process.env.S3) {
  Meteor.settings.s3 = JSON.parse(process.env.S3).s3;
}

if (!Meteor.settings.debug) {
  Meteor.settings.debug = process.env.DEBUG === 'true' ? true : false;
}

// const s3Conf = Meteor.settings.s3 || {};
const s3Conf = {  //jwpark 계정
  "key": "-",
  "secret": "-",
  "bucket": (function() {
    if (___MODE == 'test' || ___MODE == 'local') {
      return 'test.zmap.or.kr'
    }
    else {
      return "youth.zmap.or.kr"
    }

  })(),
  "region": "ap-northeast-2"
}

if (s3Conf && s3Conf.key && s3Conf.secret && s3Conf.bucket && s3Conf.region) {
  useS3  = true;

  /* AWS:S3 CLIENT INSTANCE
   * @type {AWS.Service}
   * @instanceof AWS.Service
   * @name client
   */
  const s3ConnectionTimeout = 6000000;
  const s3Retries = 4;
  client = new S3({
    secretAccessKey: s3Conf.secret,
    accessKeyId: s3Conf.key,
    region: s3Conf.region,
    maxRetries: s3Retries,
    sslEnabled: false,
    correctClockSkew: true,
    httpOptions: {
      connectTimeout: s3ConnectionTimeout,
      timeout: s3ConnectionTimeout * s3Retries
    }
  });

  // TEST WRITE/READ/REMOVAL ACCESS TO AWS:S3 ENDPOINT
  const rndmName = Random.id();
  client.putObject({
    Bucket: s3Conf.bucket,
    Key: `test-file-${rndmName}.txt`,
    Body: Buffer.from('text text file', 'utf8')
  }, (awsWriteError) => {
    bound(() => {
      if (awsWriteError) {
        throw new Meteor.Error(500, 'Achtung! No WRITING access to AWS:S3 storage', awsWriteError);
      } else {
        client.getObject({
          Bucket: s3Conf.bucket,
          Key: `test-file-${rndmName}.txt`,
        }, (awsReadError) => {
          bound(() => {
            if (awsReadError) {
              throw new Meteor.Error(500, 'Achtung! No READ access to AWS:S3 storage', awsReadError);
            } else {
              client.deleteObject({
                Bucket: s3Conf.bucket,
                Key: `test-file-${rndmName}.txt`,
              }, (awsRemoveError) => {
                bound(() => {
                  if (awsRemoveError) {
                    throw new Meteor.Error(500, 'Achtung! No REMOVAL access to AWS:S3 storage', awsRemoveError);
                  }
                });
              });
            }
          });
        });
      }
    });
  });
}

Files = new FilesCollection({
  // debug: Meteor.settings.debug,
  debug: false, // Change to `true` for debugging
  continueUploadTTL: 32400, // Limit upload to 9 hours (by default 3 hours), since we allow 3GB in our demo app, it might take time on slow connection to upload it
  // storagePath: Meteor.settings.storagePath || 'assets/app/uploads/uploadedFiles',
  storagePath: `${process.env.HOME}/hdd/files`,
  // collectionName: 'uploadedFiles',
  collectionName: 'files',
  allowClientCode: true,
  // disableUpload: true,
  // disableDownload: true,
  onBeforeUpload() {
    // if (file.size <= 10485760 && /png|jpg|jpeg|gif|tif/i.test(file.extension)) return true;
    if (file.size <= 10485760*2) return true;
    return '업로드 파일은 20MB 까지 가능합니다.';

    // if (this.file.size <= _app.conf.maxFileSize) {
    //   return true;
    // }
    // return `Max. file size is ${filesize(_app.conf.maxFileSize).replace('.00', '')} you've tried to upload ${filesize(this.file.size)}`;
  },
  interceptDownload(http, fileRef, version) {
    let path;
    if (useS3) {
      path = (fileRef && fileRef.versions && fileRef.versions[version] && fileRef.versions[version].meta && fileRef.versions[version].meta.pipePath) ? fileRef.versions[version].meta.pipePath : void 0;
      if (path) {
        // If file is successfully moved to Storage
        // We will pipe request to Storage
        // So, original link will stay always secure

        // To force ?play and ?download parameters
        // and to keep original file name, content-type,
        // content-disposition and cache-control
        // we're using low-level .serve() method
        const opts = {
          Bucket: s3Conf.bucket,
          Key: path
        };

        if (http.request.headers.range) {
          const vRef = fileRef.versions[version];
          let range = _app.clone(http.request.headers.range);
          const array = range.split(/bytes=([0-9]*)-([0-9]*)/);
          const start = parseInt(array[1]);
          let end = parseInt(array[2]);

          if (isNaN(end)) {
            // Request data from AWS:S3 by small chunks
            end = (start + this.chunkSize) - 1;
            if (end >= vRef.size) {
              end = vRef.size - 1;
            }
          }

          opts.Range = `bytes=${start}-${end}`;
          http.request.headers.range = `bytes=${start}-${end}`;
        }

        const responseEnd = (error) => {
          bound(() => {
            if (error) {
              console.error('[interceptDownload] [responseEnd]', error);
            }

            if (!http.response.finished) {
              http.response.end();
            }
          });
        };

        const awsStream = client.getObject(opts).createReadStream();
        awsStream.on('error', responseEnd);

        this.serve(http, fileRef, fileRef.versions[version], version, awsStream);
        return true;
      }
      // While file is not yet uploaded to Storage
      // We will serve file from FS
      return false;
    }
    return false;
  }
});

Files.denyClient();
Files.on('afterUpload', function(fileRef) {
  const messageObj = {
    title: `File: ${fileRef.name}`,
    body: 'Successfully uploaded. Click to view',
    data: {
      url: `/f/${fileRef._id}`
    }
  };

  // let webPushSubscription = false;
  // if (fileRef.meta.subscription) {
  //   webPushSubscription = fileRef.meta.subscription;
  // }

  if (useS3) {
    for(let version in fileRef.versions) {
      if (fileRef.versions[version]) {
        const vRef = fileRef.versions[version];
        // We use Random.id() instead of real file's _id
        // to secure files from reverse engineering
        // As after viewing this code it will be easy
        // to get access to unlisted and protected files
        // const filePath = `files/${Random.id()}-${version}.${fileRef.extension}`;
        const filePath = 'files/' + (fileRef._id) + '-' + version + '.' + fileRef.extension; //for convenience

        client.putObject({
          StorageClass: 'STANDARD',
          Bucket: s3Conf.bucket,
          Key: filePath,
          Body: fs.createReadStream(vRef.path),
          ContentType: vRef.type,
        }, (error) => {
          bound(() => {
            if (error) {
              console.error('[afterUpload] [putObject] Error:', error);
            } else {
              const upd = {
                $set: {
                  [`versions.${version}.meta.pipePath`]: filePath
                }
              };

              // if (webPushSubscription) {
              //   upd.$unset = {
              //     'meta.subscription': ''
              //   };
              // }

              this.collection.update({
                _id: fileRef._id
              }, upd, (updError) => {
                if (updError) {
                  console.error('[afterUpload] [putObject] [collection.update] Error:', updError);
                } else {
                  // Unlink original file from FS
                  // after successful upload to AWS:S3
                  this.unlink(this.collection.findOne(fileRef._id), version);
                  // if (webPushSubscription) {
                  //   webPush.send(webPushSubscription, messageObj);
                  // }
                }
              });
            }
          });
        });
      }
    }
  // } else if (webPushSubscription) {
  //   webPush.send(webPushSubscription, messageObj);
  //   Files.collection.update({
  //     _id: fileRef._id
  //   }, {
  //     $unset: {
  //       'meta.subscription': ''
  //     }
  //   });
  }
});

// This line now commented due to Heroku usage
// Files.collection._ensureIndex {'meta.expireAt': 1}, {expireAfterSeconds: 0, background: true}
Files.collection._ensureIndex({'meta.expireAt': 1}, {background: true});

// Intercept FileCollection's remove method
// to remove file from AWS S3
if (useS3) {
  const _origRemove = Files.remove;
  Files.remove = function(search) {
    const cursor = this.collection.find(search);
    cursor.forEach((fileRef) => {
      for (let version in fileRef.versions) {
        if (fileRef.versions[version]) {
          const vRef = fileRef.versions[version];
          if (vRef && vRef.meta && vRef.meta.pipePath) {
            client.deleteObject({
              Bucket: s3Conf.bucket,
              Key: vRef.meta.pipePath,
            }, (error) => {
              bound(() => {
                if (error) {
                  console.error('[remove] [deleteObject] Error:', error);
                }
              });
            });
          }
        }
      }
    });
    // Call original method
    _origRemove.call(this, search);
  };
}

// Remove all files on server load/reload, useful while testing/development
// Meteor.startup -> Files.remove {}

// Remove files along with MongoDB records two minutes before expiration date
// If we have 'expireAfterSeconds' index on 'meta.expireAt' field,
// it won't remove files themselves.
// Meteor.setInterval(() => {
//   Files.remove({
//     'meta.expireAt': {
//       $lte: +new Date(+Date.now() + 120000)
//     }
//   }, _app.NOOP);
// }, 120000);


// Files.insertFile = function(file) {
//   const upload = Files.insert({file: file}, false);
//   upload.on('start', function() {
//     startSpinner()
//   })
//   upload.on('end', function(error, fileObj) {
//     if (error) {
//       alert('파일 업로드 중 오류가 발생 했습니다. 고객센터에 문의 해 주세요. ' + error)
//     }
//     stopSpinner()
//   })
//   upload.start()
//   return upload.config.fileId;
// }
```

**Comment by kakadais** [comment] 2020-11-09 09:40
I understand that there's mixed Server/Client side code, 
but I don't think your example has problem cause Meter-Files example is working correctly.

Please tell me what did I miss if you can get-

**Comment by kakadais** [comment] 2020-11-09 09:51
Sorry for too many writing.

I've fixed _ensureIndex to the server code,
and fs-extra to fs things.

And the project started to working but have some CORS problem for aws package.
![image](https://user-images.githubusercontent.com/5265343/98525855-680fe400-22bc-11eb-8d1b-989aad5363a1.png)

**Comment by dr-dimitru** [comment] 2020-11-09 11:20
@kakadais I see only the single issue through all your messages — you importing Server codebase on the Client.
Most of code in this thread supposed to be on a Server. You got to follow [exact-code-splitting technique](https://github.com/veliovgroup/meteor-snippets/tree/main/exact-code-splitting) *work on that tutorial is still in progress*

**Comment by kakadais** [comment] 2020-11-10 09:14
Agree-
Now I understand my missing point.

And I think some of people might get confused on this when they follow & update Meteor-Files by the sample code,
have you any plan to update Docs or Examples a little bit simple?
(Simple which means pacakge independent examples to update Meteor-Files to new version)

I'll catch up and leave a result later-
(You could close then I'll re-open if it's nessasary-)

**Comment by dr-dimitru** [comment] 2020-11-10 21:08
@kakadais Most of code-samples are stated "Shared code"/"Client's code"/"Server's code" unless it's obvious like using HTML/JADE/CSS which is always *Client*.

Let me know what part of the examples got you confused. *Note: Many docs, tutorials, and examples provided by community members, feel free to contribute to the documentation too*

**Comment by dr-dimitru** [comment] 2020-11-20 22:26
@kakadais closing this issue for now.
Feel free to reopen it in case if the issue is still persists on your end.

**Closed by dr-dimitru** 2020-11-20 22:26 UTC
Labels: question
