### ISSUE TITLE
Google Cloud Storage example is no longer working

### ISSUE THREAD

**Issue by martinderm** [VeliovGroup/Meteor-Files#684] opened 2019-04-17 13:04 UTC
I followed the Google Cloud Storage Guide. The recommended module google-cloud is deprecatd and the suggested alternative @google-cloud/storage doesn't work with meteor's nodeJS version (worker_threads module is missing)

What can I do to use google cloud storage today?

**Comment by jankapunkt** [comment] 2019-05-24 08:16
>  @google-cloud/storage doesn't work with meteor's nodeJS version 

@martinderm which Meteor release do you use? Which node version is it?

```
meteor node -v
```

Unfortunately worker threads is also marked as [Stability: 1 - Experimental](https://nodejs.org/api/worker_threads.html) so I doubt it will be soon part of Meteor as they build mostly against stable LTS node releases.

**Comment by dr-dimitru** [comment] 2019-05-24 14:48
Hello @martinderm 

> The recommended module google-cloud is deprecatd and the suggested alternative @google-cloud/storage

It's __only recommendation__ for now, you're safe to use method described in Google Cloud Storage Guide. We will update tutorial as soon as Meteor will get node.js upgrade.

/CC @amos-whitewolf @jeremywrnr @salmanhasni

**Comment by salmanhasni** [comment] 2019-05-24 16:15
@dr-dimitru @martinderm I agree with you, google-cloud is depreciate, we should update the docs

**Comment by jeremywrnr** [comment] 2019-05-24 19:04
Using `@google-cloud/storage` worked for me, though you do have to update the code integration from the [current documentation example](https://github.com/VeliovGroup/Meteor-Files/wiki/Google-Cloud-Storage-Integration) to get it to work.

This was helpful:
https://cloud.google.com/storage/docs/uploading-objects#storage-upload-object-nodejs

Versions:

    meteor node -v    # v8.15.1
    meteor --version # Meteor 1.8.1

**Comment by jankapunkt** [comment] 2019-05-25 07:31
> Using @google-cloud/storage worked for me

@jeremywrnr how did you resolve the `worker_threads module missing` error that @martinderm reported in the initial post?

**Comment by jeremywrnr** [comment] 2019-05-28 00:51
I didn't encounter that error. Maybe it is the node/meteor version that @martinderm used?

**Comment by martinderm** [comment] 2019-05-28 10:02
I was using the latest meteor for macOS at the time of posting that arrives with standard installation procedure and updates. It probably was NodeJS 8.11.4 
According to this blogpost worker threads are introduced with nodejs 10.5 and after that discovery I gave up on the topic. https://blog.logrocket.com/node-js-multithreading-what-are-worker-threads-and-why-do-they-matter-48ab102f8b10

My colleague how is more inclined to solve such problems found a solution that involved pinning some old version of some module which is of course a not so fine solution.

**Comment by dr-dimitru** [comment] 2019-06-06 13:09
@jeremywrnr I believe it's safe to try running on `node@10.5.*`

**Comment by salmanhasni** [comment] 2019-06-26 20:58
https://github.com/VeliovGroup/Meteor-Files/pull/698

**Comment by dr-dimitru** [comment] 2019-06-29 11:05
Fixed by #699, 
Feel free to reopen it in case if the issue is still persists on your end.

**Closed by dr-dimitru** 2019-06-29 11:05 UTC
Labels: Documentation, Google Cloud
