### ISSUE TITLE
File transfer gets paused while trying to upload

### ISSUE THREAD

**Issue by timsun28** [veliovgroup/Meteor-Files#828] opened 2021-11-28 12:43 UTC
### I'm having an issue:
I'm developing an online/offline app that allows you to take pictures that get uploaded to an S3 bucket. 
I have implemented this feature using meteor files and when online all is working properly and as expected. 
For the offline functionality I have implemented a check in case the device is offline that the picture gets stored in local storage. 
Afterwards using the online event I go through all the local storage pictures and run the same code as for the online upload. 

While testing this using the online/offline debug tools under the network tab in chrome devtools I was able to take a picture and upload it when I turned off the offline mode. However when I try the same on an android 12 device (firefox) by actually turning off wifi and after taking the picture turning it back online the file doesn't get uploaded. 

I tried to debug the issue myself, but the only clue I got from the console logs is that the transfer gets paused for some reason. 

```
[FilesCollection] [insert()]
[FilesCollection] [FileUpload] [constructor]
[FilesCollection] [insert] [Tracker] [pause]
[FilesCollection] [insert] [.pause()]
[FilesCollection] [insert] using WebWorkers
upload.on('started') trigger runs
upload.on('started') error result: null
```

The other triggers like uploaded and end never run and don't console log the errors.

Could anyone think of a better way to debug this issue or know what might be wrong? 
Creating a working demo of the issue will take some time unfortunately, but if we can't figure this out I will do my best to create one. 
 
Meteor files version: 1.14.3
Meteor version: 2.5

I just noticed that there is a version 2.0 out already, I will give this a shot and see if this could fix the issue.

**Comment by timsun28** [comment] 2021-11-28 13:21
I updated the package version to 2.0.1 and removed the stream property from the upload object. 
Tested the same process and it has now successfully uploaded my file to the bucket as intended. 

It seemed like a bug with the old version and has been fixed in the new version.

**Comment by dr-dimitru** [comment] 2021-11-28 20:00
Hello @timsun28 ,

I'm glad this was so easily solved 🥳
Feel free to close it in case if the issue is solved on your end.

**Closed** 2021-11-28 20:02 UTC
Labels: question, Solved
