### ISSUE TITLE
Cannot enable caching

### ISSUE THREAD

**Issue by joaomframos** [VeliovGroup/Meteor-Files#671] opened 2019-02-01 12:52 UTC
I am currently attempting to enable caching for the images requests I have uploaded to my server (and were saved with gridfs) but every request has **Cache-Control: no-cache** specified as a request header, fully preventing the caching.

Currently, my FilesCollection config has cacheControl set as 'public, max-age=31536000' and I also attempted to override the responseHeaders function (maintaining the base code, just adding a rule for cache-control) and none had an effect.

The uploaded files (images) are being loaded directly into the html via the 'src' attribute with the link provided by document uploaded with Gridfs.

I have checked every WebApp.rawConnectHandler that my app is running and none is setting this header. I have a hunch that the issue may be somehow related to Meteor as I have the same headers specified on Meteor specific requests without a clear reason for it.

During a couple of tests, I noticed that if the image is loaded from a localhost (either the app that is answering the request or another one, running in another port) this issue does happen but if I load the image from any other webpage this header is no longer set. In all of these cases the image is added to the HTML with the approach described above.

Meteor-Files version: 1.10.2
Meteor version: 1.8.0.2
System: Linux
Browser: Chrome 71
Client issue

**Comment by macrozone** [comment] 2019-03-01 12:44
@joaomframos check my last comment: https://github.com/VeliovGroup/Meteor-Files/issues/616

maybe you used the wiki entry here to implement gridfs, but its missing the cache controls header

**Comment by dr-dimitru** [comment] 2019-06-19 21:36
Hello @joaomframos,

>  I noticed that if the image is loaded from a localhost (either the app that is answering the request or another one, running in another port) this issue does happen but if I load the image from any other webpage this header is no longer set

Shall we assume this issue as solved?
Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment] 2019-07-08 13:17
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Closed by dr-dimitru** 2019-07-08 13:17 UTC
Labels: GridFS, question
