### ISSUE TITLE
The link of files while streaming is misbehaving when server is restarted

### ISSUE THREAD

**Issue by GSYamaji** [veliovgroup/Meteor-Files#794] opened 2021-04-05 11:45 UTC
### Here is the explanation of the issue I ma facing:
  - I am using the `{{HelperFunction.link}}` method to stream files on Client side. The problem is when the server is restarted this function returns a link but the link is not pointing to the desired file. The app is not deployed and the MongoDB and Meteor app are both running on localhost. Moreover when I use different device on the same network to access the app, I face the same issue. Is there another way to show or access the file, maybe by using the `data=""` property of html tags. 
  - I am unable to retrieve `ostrio:files` package version 
  - Meteor v2.1
  - Windows(Microsoft Edge v89.0.774.68)
  - I think this is an issue with the link. I had like to know if we can retrieve the file in form of Data

### Shared
```
const ImageSchema = Object.assign({}, FilesCollection.schema, {
    timestamp: {
        type: Number,
        optional:true,
    },
    username: {
        type: String,
        optional:true,
    },
    chatRoomsID: {
        type: String,
        optional: true
    }
  });
Images = new FilesCollection({
    collectionName: 'Images',
    schema: ImageSchema
  });
Images.collection.attachSchema(new SimpleSchema(ImageSchema));
```
### Client Side
HTML
```
<img src="{{imageFile.link}}" alt="{{name}}" style="width: 100%; height: 300px;">
```
Client JS
```
Template.chatroomid.onRendered(function(){
imageFile() {
         Meteor.subscribe('Images');
      }
});
Template.chatroomid.helpers({
imageFile() {
        return Images.findOne({_id:`${this._id}`});
      }
});
```
### Server Side
```
Meteor.publish('Images', function tasksPublication() {
    return Images.find().cursor;
  });
```

**Comment by dr-dimitru** [comment] 2021-04-05 19:16
@GSYamaji that saounds like subscription isn't ready upon server reload. But still not sure why are you experiencing this. Using [`fileURL` template helper](https://github.com/veliovgroup/Meteor-Files/wiki/Template-Helper) might help you to solve this, please, let me know after you try.

**Comment by GSYamaji** [comment] 2021-04-06 07:10
> @GSYamaji that sounds like subscription isn't ready upon server reload. But still not sure why are you experiencing this. Using [`fileURL` template helper](https://github.com/veliovgroup/Meteor-Files/wiki/Template-Helper) might help you to solve this, please, let me know after you try.

@dr-dimitru thank you for the advice. I have tried the template helper and the problem still stands. then it must be the subscription. I am subscribing to published document in .onRendered() event. If that is causing the problem where should i subscribe. 
To help you understand the case, here is the link generated when I upload the file
[http://localhost:3000/cdn/storage/Images/Gdvu96DhcjHb3B9Fo/original/Gdvu96DhcjHb3B9Fo.jpg](url) 
and it works fine
after sometime this link does not return any file.

**Comment by dr-dimitru** [comment] 2021-04-06 18:58
> after sometime this link does not return any file

Okay I believe you ran into [this condition described in our FAQ](https://github.com/VeliovGroup/Meteor-Files#faq):

> __Note: All files will be removed as soon as your application rebuilds or you run__ `meteor reset`. To keep your storage persistent during development use an absolute path outside of your project folder, e.g. `/data` directory.

**Comment by GSYamaji** [comment] 2021-04-08 14:52
Thanks It does work and that was exactly what I was missing.
Though I have a Question. What if I store files in the Public/Files/
I want to make clear that Public is a folder in the root directory of my project.

**Comment by dr-dimitru** [comment] 2021-04-08 19:41
@GSYamaji 

> Though I have a Question. What if I store files in the Public/Files/
> I want to make clear that Public is a folder in the root directory of my project.

No guarantee it won't get removed. Even for production environment it's always a good practice to keep uploaded files out of project's codebase directory, as it might get wiped during deployment.

**Comment by dr-dimitru** [comment] 2021-04-16 18:51
@GSYamaji Feel free to close it in case if the issue is solved on your end.

**Comment by GSYamaji** [comment] 2021-04-16 19:45
Thank you very much @dr-dimitru. You were very helpful and the issue was resolved

**Closed** 2021-04-16 19:44 UTC
Labels: .link(), question
