### ISSUE TITLE
How to show progress of file uploading to aws on client side?

### ISSUE THREAD

**Issue by ashishdeligence234** [VeliovGroup/Meteor-Files#685] opened 2019-05-01 12:23 UTC
Thank you for this amazing package of file/directory uploading, but, I want some help.

I am uploading directory on aws in onAfterUpload hook and this hook run on server that's why i am not able to show upload progress on client side. please help me i am stuck here in my project from last few weeks.

Meteor version 1.8
ostrio:files@1.10.2

**Comment by jankapunkt** [comment] 2019-05-24 08:07
You could use another `Mongo.Collection` (let's name it 'awsProgress') and create a temporary document in `onAfterUpload`. Then you listen to the AWS Upload progress and update the progress document respectively. Your client can subscribe to this document and should see the AWS Upload progress.

**Comment by jankapunkt** [comment] 2019-05-24 08:26
related: https://github.com/VeliovGroup/Meteor-Files/issues/678

**Comment by dr-dimitru** [comment] 2019-05-24 14:44
@ashishdeligence234 I'll add some explanation:

Files library always uses your main server where meteor's node.js process is running as intermediate, that means file got to be __fully uploaded__ to your server first, then to the final storage — AWS:S3 in your case.

**Comment by dr-dimitru** [comment] 2019-06-06 13:07
@ashishdeligence234 let me know if you need any additional info. 
Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment] 2019-06-19 21:32
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Closed by dr-dimitru** 2019-06-19 21:32 UTC
Labels: .insert() (upload), AWS S3, question
