### ISSUE TITLE
Uploading to another Server via DDP connection - small file immediately deleted again

### ISSUE THREAD

**Issue by Twisterking** [VeliovGroup/Meteor-Files#680] opened 2019-04-03 13:42 UTC
So I am using this awesome package to upload files to a worker-server of mine like so:

```js
{
  // ...
  transport: 'ddp',
  ddp: <myDDPconnection returned from DDP.connect()>,
  streams: 'dynamic',
  chunkSize: 'dynamic',
  // ...
}
```

For larger files this works just fine, but for some reason for smaller files, these are immediately deleted again after a successful upload. very weird!

**Changing the following solved the issue for me**:
```js
{
  // ...
  transport: 'ddp',
  ddp: <myDDPconnection returned from DDP.connect()>,
  streams: 1,
  chunkSize: 100,
  // ...
}
```

Maybe someone can fix this? 😄

**Comment by jamalcoder** [comment] 2019-04-05 00:50
hello @Twisterking i think you have just to play with streams and chunkSize, and in my vue it's better to use http because ddp protocol is slow.

**Comment by jankapunkt** [comment] 2019-05-24 08:21
Is this a reproducible error or rather a config issue?

**Comment by Twisterking** [comment] 2019-05-24 11:00
Not sure, I can only tell you that it definitely solved my problem to change the `streams` and `chunkSize` - with 'dynamic' like 8 out of 10 times the file was immediately deleted afterwards.

**Comment by dr-dimitru** [comment] 2019-06-06 13:12
Hello @Twisterking,
This issue should be fixed in [`v1.11.0`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.11.0), please update to the latest release and let me know if issue is solved.
Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment] 2019-06-26 13:10
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Closed by dr-dimitru** 2019-06-26 13:10 UTC
Labels: .insert() (upload), bug, question

**Comment by Twisterking** [comment] 2020-02-19 11:34
Hello there,
For completely unrelated reasons, I just played around with the code in question again. I am currently on version `1.13.0` and the **bug persists** - changing both options to 'dynamic' results in a file which is immediately deleted again.

**Comment by dr-dimitru** [comment] 2020-03-20 14:57
@Twisterking need more details including logs and etc. better to start new issue thread with following our default bug report template. Thank you
