### ISSUE TITLE
Feature Request: Get relative path of the file without the domain part of the url 

### ISSUE THREAD

**Issue by schlaegerz** [VeliovGroup/Meteor-Files#626] opened 2018-06-27 19:48 UTC
I have a specific case where I need to just pass around the path, and now I have to do some annoying string operations to make sure that I get the correct url after I user item.link()

Is this something that already exists?

**Comment by aureooms** [comment] 2018-07-01 18:56
Related: [currently the download root is based on meteor's environment variables](https://github.com/VeliovGroup/Meteor-Files/blob/c97072537f4475fb4c93b112d3f8baa24343a6fa/lib.js#L68). I have a case where I want to derive it from `window.location`.

**Comment by dr-dimitru** [comment] 2018-07-23 00:16
Hey guys @schlaegerz @aureooms ,
Hope it isn't too late, this feature have been implemented, as third argument for [`fileURL` helper](https://github.com/VeliovGroup/Meteor-Files/wiki/Template-Helper#change-base-uri-pass-third-argument-uribase), [`FilesCollection#link()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/link), and [`FileCursor#link()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/FileCursor#methods) in [`v1.10.0`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.10.0).

Let me know wdyt, ok?

**Comment by schlaegerz** [comment] 2018-07-24 16:05
This is great thank you!

**Comment by dr-dimitru** [comment] 2018-07-24 17:32
@schlaegerz thank you for checking, and thank you for contribution. Closing as solved/implemented.
Feel free to reopen it in case if the issue is still persists on your end.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)

**Closed by dr-dimitru** 2018-07-24 17:32 UTC
Labels: enhancement
