### ISSUE TITLE
where is RemoveFile and RenameFile in React example

### ISSUE THREAD

**Issue by RonenHong** [VeliovGroup/Meteor-Files#638] opened 2018-08-24 04:25 UTC
Hi, 
I ran React example, it works well, but where is RemoveFile and RenameFile?
it says in assumption 'You have Meteor methods for RemoveFile and RemoveFile' in wiki
(BTW, there is typo, latter RemoveFile should be RenameFile)

**Comment by dr-dimitru** [comment] 2018-08-24 09:48
Hello @RonenHong ,

Thank you for reporting about this. React docs and examples supported by community members.
Hope @vtocco and @mikkelking will help us here.

If you wish to update/correct current example, feel free to send a PR, [here is original article](https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/react-example.md).

**Comment by mikkelking** [comment] 2018-08-24 13:44
@RonenHong I have made a PR for this, #639 
The assumption is that you will provide Meteor methods for `RemoveFile` and `RenameFile` They are not provided as such, because it is up to you to decide on collection names, and any permissions related to these operations.

**Comment by dr-dimitru** [comment] 2018-08-24 15:34
@mikkelking thank you for quick response
@RonenHong is this issue solved?

**Comment by RonenHong** [comment] 2018-08-25 00:11
@dr-dimitru @mikkelking I already implemented 'RemoveFile' using remove() function, but how can I change the name, just update file name to Collection?

**Comment by mikkelking** [comment] 2018-08-26 01:44
We should close this ticket now

**Comment by dr-dimitru** [comment] 2018-08-26 11:46
Feel free to reopen it in case if the issue is still persists on your end.

**Closed by dr-dimitru** 2018-08-26 11:46 UTC
Labels: Documentation, React, help wanted
