### ISSUE TITLE
x_mtok - Some cookies are misusing the recommended “SameSite“ attribute 

### ISSUE THREAD

**Issue by jankapunkt** [veliovgroup/Meteor-Files#759] opened 2020-10-06 07:24 UTC
#### Give an expressive description of what is went wrong

Firefox is giving me the following message when starting an application that uses this package:

> Some cookies are misusing the recommended “SameSite“ attribute

> Cookie “x_mtok” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

I searched the related cookie issues in this repo but they do not cover this one, since the cookie itself works fine. I am just concerned about the content of the warning.

#### Version of `Meteor-Files` you're experiencing this issue

1.14.2

#### Version of `Meteor` you're experiencing this issue

1.11

#### Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?

- Firefox 81.0 (64-bit) all OS
- Tested with Chrome, which does not raise this issue

#### Is it *Client* or *Server* issue?

Client

#### Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
  
No additional info using debug that relates to the cookies

**Comment by dr-dimitru** [comment] 2020-10-22 00:28
@jankapunkt should be fixed in v1.14.3

Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment] 2020-10-23 11:22
Feel free to reopen it in case if the issue is still persists on your end.

**Closed by dr-dimitru** 2020-10-23 11:22 UTC
Labels: bug
